import SwiftUI
import SprossKern

/// The reading half of the numbers overview: the generated table, and the
/// handful of prose notes beside it. State lives on NumbersOverview; split out
/// purely for file size.
extension NumbersOverview {

    // MARK: - How this language counts

    /// Every row is generated by `Trainer.reference` from the same packs the
    /// drill grades against, so the page cannot claim one reading and mark
    /// another. Kern names the bands; the heading each band gets is chrome and
    /// is resolved here.
    var referenceSection: some View {
        VStack(alignment: .leading, spacing: DL.Space.l) {
            heading("numbers.reference")
            ForEach(Array(Trainer.shared.reference(language: language).enumerated()),
                    id: \.offset) { _, section in
                band(section)
            }
        }
    }

    private func band(_ section: ReferenceSection) -> some View {
        VStack(alignment: .leading, spacing: DL.Space.s) {
            if let title = Self.bandTitle(section.key) {
                Text(title)
                    .font(DL.Fonts.caption)
                    .foregroundStyle(Color.dlTextSecondary)
                    .textCase(.uppercase)
                    .accessibilityAddTraits(.isHeader)
            }
            VStack(alignment: .leading, spacing: DL.Space.xs) {
                ForEach(Array(section.entries.enumerated()), id: \.offset) { _, entry in
                    row(entry)
                }
            }
            .padding(DL.Space.l)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(
                RoundedRectangle(cornerRadius: DL.Radius.tile, style: .continuous)
                    .fill(Color.dlSurface)
            )
        }
    }

    /// Value and reading on one line, and on two once the type grows: the value
    /// column is sized by the longest one in the whole table (`1 000 000 000`),
    /// so the readings line up without a Grid that would collapse at
    /// accessibility sizes. `fixedSize` lets a long reading wrap instead of
    /// truncating — this is the page a learner reads the language off.
    private func row(_ entry: ReferenceEntry) -> some View {
        ViewThatFits(in: .horizontal) {
            HStack(alignment: .firstTextBaseline, spacing: DL.Space.m) {
                value(entry)
                reading(entry)
                Spacer(minLength: 0)
            }
            VStack(alignment: .leading, spacing: 0) {
                value(entry)
                reading(entry)
            }
        }
        .padding(.vertical, 2)
        // why: one row is one VoiceOver stop — "1 000 → eintausend", not two
        // stops that have to be paired by ear.
        .accessibilityElement(children: .combine)
    }

    private func value(_ entry: ReferenceEntry) -> some View {
        Text(verbatim: entry.value)
            .font(DL.Fonts.body)
            .monospacedDigit()
            .foregroundStyle(Color.dlTextSecondary)
    }

    private func reading(_ entry: ReferenceEntry) -> some View {
        Text(verbatim: entry.reading)
            .font(DL.Fonts.headline)
            .foregroundStyle(Color.dlTextPrimary)
            .fixedSize(horizontal: false, vertical: true)
    }

    /// Kern's band key → its heading. A key this build has no wording for still
    /// gets its rows: a new band must be able to land in kern first.
    private static func bandTitle(_ key: String) -> LocalizedStringKey? {
        let known = ["ones", "teens", "tens", "twenties",
                     "compounds", "hundreds", "places", "forms"]
        return known.contains(key) ? LocalizedStringKey("numbers.section.\(key)") : nil
    }

    // MARK: - What to watch out for

    /// Two to four lines per language, in the reader's own language where one
    /// was written and English otherwise — the same fallback the alphabet
    /// sheet's teaching aids follow.
    @ViewBuilder
    var notesSection: some View {
        let lines = NumbersOverviewNotes.lines(language: language, reader: model.sourceLanguage)
        if !lines.isEmpty {
            VStack(alignment: .leading, spacing: DL.Space.l) {
                heading("numbers.notes")
                VStack(alignment: .leading, spacing: DL.Space.m) {
                    ForEach(Array(lines.enumerated()), id: \.offset) { _, line in
                        HStack(alignment: .firstTextBaseline, spacing: DL.Space.s) {
                            Text(verbatim: "·")
                                .foregroundStyle(Color.dlTextSecondary)
                                .accessibilityHidden(true)
                            Text(verbatim: line)
                                .font(DL.Fonts.subheadline)
                                .foregroundStyle(Color.dlTextPrimary)
                                .fixedSize(horizontal: false, vertical: true)
                        }
                    }
                }
                .padding(DL.Space.l)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(
                    RoundedRectangle(cornerRadius: DL.Radius.tile, style: .continuous)
                        .fill(Color.dlSurface)
                )
            }
        }
    }
}
