import SwiftUI
import SprossKern

/// The Numbers hub entry: a numbers page for the language being learned, and
/// the place its drill is started from.
///
/// Three sections, in this order — start first, reference after: the run to
/// practice with (what it asks, how it is played, the button), then what this
/// language does with numbers (a table generated by kern, never authored) and
/// the handful of things that trip a learner up. Reading matter and the drill
/// it prepares you for are one surface, so looking something up is not five
/// taps into a running drill — but the drill is what the page is opened for,
/// so nobody scrolls past twenty screens of table to reach it.
///
/// Nothing here is graded and nothing is stored: the variant and modifier picks
/// last as long as the screen does. What DOES persist is the other way round —
/// `TrainerProgress` holds the highest Sprosse each variant ever reached, and this
/// screen only reads it, to say which rows have been earned.
///
/// The rows and toggles live in NumbersOverview+Practice.swift, the table and
/// the notes in NumbersOverview+Reference.swift; split purely for file size.
struct NumbersOverview: View {
    let model: AppModel
    /// The language being learned: what the table describes, and what the run
    /// is answered in.
    let language: String
    /// The frames a sentence run would draw from and the side they are prompted
    /// from — nil where the pair realizes none, and then Phrases is not offered.
    let phraseDrill: (source: String, templates: [PhraseTemplate])?

    @Environment(\.dismiss) private var dismiss
    @Environment(\.locale) var locale

    /// The highest Sprosse ever reached per variant in THIS language — the one
    /// source the unlock ladder reads. Held in state rather than read per row so
    /// a run that just booked a Sprosse refreshes the whole ladder in one place.
    // why: internal, not private — +Practice.swift renders the ladder from it.
    @State var progress: [DrillVariant: Int] = [:]
    /// Never empty in practice; `Los` is disabled while it is.
    @State var picked: Set<DrillVariant> = [.numbers]
    @State var modifiers: Set<DrillModifier> = []
    @State private var launch: Launch?
    /// What the run that just closed came to. Shown as one tile above the picks
    /// instead of a screen of its own — three figures do not earn a page, and a
    /// page they do not earn is one more ✕ before the next run.
    // why: internal, not private — the DEBUG hook seeds it for screenshots.
    @State var lastRun: DrillRunResult?

    /// The run the start button opens, wrapped so ONE `fullScreenCover(item:)`
    /// carries it. A cover rather than a push: a drill is a full screen with its
    /// own close, and this is the only presenter on this view — the stacked-cover
    /// hazard the hub documents is about two of them on one view.
    private struct Launch: Identifiable {
        let mode: TrainerSessionView.Mode
        let id = UUID()
    }

    /// Scroll target for the tile a closed run leaves.
    static let resultAnchor = "result"

    var body: some View {
        NavigationStack {
            ScrollViewReader { scroll in
                ScrollView {
                    LazyVStack(alignment: .leading, spacing: DL.Space.xl) {
                        if let lastRun {
                            DrillResultTile(result: lastRun)
                                .id(Self.resultAnchor)
                        }
                        practiceSection
                        referenceSection
                        notesSection
                    }
                    .padding(DL.Space.xl)
                }
                // why: a tile inserted ABOVE the content keeps the scroll offset,
                // so what a run came back with would sit off the top of a page the
                // learner is still looking at. The page comes up to meet it.
                .onChange(of: lastRun) { _, run in
                    guard run != nil else { return }
                    withAnimation(.easeOut(duration: 0.25)) {
                        scroll.scrollTo(Self.resultAnchor, anchor: .top)
                    }
                }
            }
            #if DEBUG
            .defaultScrollAnchor(Self.uitestAnchor)
            #endif
            .background(Color.dlBackground.ignoresSafeArea())
            .navigationTitle(Text("numbers.title \(languageName)"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar { overviewToolbar }
        }
        .tint(.dlAccent)
        .onAppear { reloadProgress() }
        // why: a closing run books its best Sprossen into TrainerProgress, so the
        // ladder behind it is stale the moment the cover comes down.
        .fullScreenCover(item: $launch, onDismiss: reloadProgress) { launch in
            TrainerSessionView(mode: launch.mode, normalizer: launch.mode.normalizer(model),
                               catalog: model.catalog, model: model,
                               onFinish: { result in
                                   withAnimation(.easeOut(duration: 0.25)) { lastRun = result }
                               })
                .environment(\.locale, model.knownLocale)
        }
        // why: the record is what the confetti is for, and it rains over the
        // page the run came back to — a wave retires itself, so no dismissal
        // and no state to clear.
        .overlay {
            if lastRun?.newRecord == true { ConfettiView().ignoresSafeArea().allowsHitTesting(false) }
        }
    }

    // MARK: - Starting a run

    /// The run the current picks describe. Phrase frames ride along whether or
    /// not Phrases is picked — `Mode` drops a frameless Phrases itself, and
    /// carrying them means the run samples from the set the screen was opened with.
    func buildMode() -> TrainerSessionView.Mode {
        TrainerSessionView.Mode(variants: DrillVariant.allCases.filter(picked.contains),
                                language: language,
                                phraseSource: phraseDrill?.source,
                                templates: phraseDrill?.templates ?? [],
                                modifiers: modifiers)
    }

    func start() {
        launch = Launch(mode: buildMode())
    }

    // MARK: - The ladder

    /// Reads every variant's stored Sprosse at once, because a requirement names a
    /// variant other than the row it gates (Phrases is bought with Clock).
    func reloadProgress() {
        var levels: [DrillVariant: Int] = [:]
        for variant in DrillVariant.allCases {
            levels[variant] = TrainerProgress.best(for: "\(variant.storageTag).\(language)")
        }
        #if DEBUG
        levels.merge(Self.uitestProgress) { _, seeded in seeded }
        #endif
        progress = levels
        normalizePicks()
        #if DEBUG
        // why: a cover raised while the sheet under it is still animating in is
        // dropped — the tap this stands in for always comes after that. ONCE:
        // this also runs when the cover comes down, and a closing run that
        // reopens itself is a screenshot run that never ends.
        if launch == nil, !Self.uitestLaunched, UserDefaults.standard.bool(forKey: "uitest-run") {
            Self.uitestLaunched = true
            Task { @MainActor in
                try? await Task.sleep(for: .milliseconds(600))
                start()
            }
        }
        #endif
    }

    // MARK: - Chrome

    /// The corners the rest of the app uses: the way out on the left, the way in
    /// on the right. The right one repeats the `Los` button on purpose — it is
    /// the one that stays reachable once the reading has been scrolled into.
    @ToolbarContentBuilder
    var overviewToolbar: some ToolbarContent {
        ToolbarItem(placement: .topBarLeading) {
            Button { dismiss() } label: { Image(systemName: "xmark") }
                .accessibilityLabel(Text("common.close"))
        }
        ToolbarItem(placement: .topBarTrailing) {
            Button("trainer.overview.start") { start() }
                .disabled(picked.isEmpty)
        }
    }

    var languageName: String {
        LanguageNames.display(language, locale: locale, catalog: model.catalog)
    }

    func heading(_ key: LocalizedStringKey) -> some View {
        Text(key)
            .font(DL.Fonts.title)
            .foregroundStyle(Color.dlTextPrimary)
            .accessibilityAddTraits(.isHeader)
    }
}

#if DEBUG
extension NumbersOverview {
    /// One auto-start per launch — see `reloadProgress`.
    @MainActor static var uitestLaunched = false

    /// `-uitest-section table|notes` opens the page in the middle of the table
    /// or at the notes under it instead of at the top — the reading sits below
    /// the fold and no thumb drives a screenshot run. The options need no hook:
    /// they are what the page opens on.
    static var uitestAnchor: UnitPoint {
        switch UserDefaults.standard.string(forKey: "uitest-section") {
        // why: the table is twenty screens long — `center` is the only way to
        // photograph a middle band, which is where the readings get long enough
        // to test the wrap.
        case "table": return .center
        case "notes": return .bottom
        default: return .top
        }
    }

    /// `-uitest-progress Numbers=7,Forms=5` stands the ladder at a Sprosse a
    /// screenshot cannot climb to by thumb. In MEMORY only: a photographed
    /// unlock must never become a stored one.
    static var uitestProgress: [DrillVariant: Int] {
        let known: [String: DrillVariant] = ["numbers": .numbers, "clock": .clock,
                                             "phrases": .phrases, "forms": .forms]
        let pairs = (UserDefaults.standard.string(forKey: "uitest-progress") ?? "")
            .split(separator: ",")
            .compactMap { entry -> (DrillVariant, Int)? in
                let parts = entry.split(separator: "=")
                guard parts.count == 2,
                      let variant = known[parts[0].trimmingCharacters(in: .whitespaces).lowercased()],
                      let level = Int(parts[1].trimmingCharacters(in: .whitespaces))
                else { return nil }
                return (variant, level)
            }
        return Dictionary(pairs) { _, last in last }
    }
}
#endif
