import SwiftUI
import SprossKern

/// The "Zahlen" hub entry: a numbers page for the language being learned, and
/// the place its drill is started from.
///
/// Three sections, in this order — reference first, options second, start last:
/// what this language does with numbers (a table generated by kern, never
/// authored), the handful of things that trip a learner up, then the run to
/// practise it with. Reading matter and the drill it prepares you for are one
/// surface, so looking something up is not five taps into a running drill.
///
/// Nothing here is graded and nothing is stored: the variant and modifier picks
/// last as long as the screen does. What DOES persist is the other way round —
/// `TrainerProgress` holds the highest rung each variant ever reached, and this
/// screen only reads it, to say which rows have been earned.
///
/// The rows and toggles live in NumbersOverview+Practice.swift, the table and
/// the notes in NumbersOverview+Reference.swift; split purely for file size.
struct NumbersOverview: View {
    let model: AppModel
    /// The language being learned: what the table describes, and what the run
    /// is answered in.
    let language: String
    /// The frames a sentence run would draw from and the side they are prompted
    /// from — nil where the pair realizes none, and then Phrases is not offered.
    let phraseDrill: (source: String, templates: [PhraseTemplate])?

    @Environment(\.dismiss) private var dismiss
    @Environment(\.locale) var locale

    /// The highest rung ever reached per variant in THIS language — the one
    /// source the unlock ladder reads. Held in state rather than read per row so
    /// a run that just booked a rung refreshes the whole ladder in one place.
    // why: internal, not private — +Practice.swift renders the ladder from it.
    @State var progress: [DrillVariant: Int] = [:]
    /// Never empty in practice; `Los` is disabled while it is.
    @State var picked: Set<DrillVariant> = [.numbers]
    @State var modifiers: Set<DrillModifier> = []
    @State private var launch: Launch?

    /// The run the start button opens, wrapped so ONE `fullScreenCover(item:)`
    /// carries it. A cover rather than a push: a drill is a full screen with its
    /// own close, and this is the only presenter on this view — the stacked-cover
    /// hazard the hub documents is about two of them on one view.
    private struct Launch: Identifiable {
        let mode: TrainerSessionView.Mode
        let id = UUID()
    }

    var body: some View {
        NavigationStack {
            ScrollView {
                LazyVStack(alignment: .leading, spacing: DL.Space.xl) {
                    referenceSection
                    notesSection
                    practiceSection
                }
                .padding(DL.Space.xl)
            }
            .background(Color.dlBackground.ignoresSafeArea())
            .navigationTitle(Text("numbers.title \(languageName)"))
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("common.done") { dismiss() }
                }
            }
        }
        .tint(.dlAccent)
        .onAppear { reloadProgress() }
        // why: a closing run books its best rungs into TrainerProgress, so the
        // ladder behind it is stale the moment the cover comes down.
        .fullScreenCover(item: $launch, onDismiss: reloadProgress) { launch in
            TrainerSessionView(mode: launch.mode, normalizer: launch.mode.normalizer(model),
                               catalog: model.catalog, model: model)
                .environment(\.locale, model.knownLocale)
        }
    }

    // MARK: - Starting a run

    /// The run the current picks describe. Phrase frames ride along whether or
    /// not Phrases is picked — `Mode` drops a frameless Phrases itself, and
    /// carrying them means the run samples from the set the screen was opened with.
    func buildMode() -> TrainerSessionView.Mode {
        TrainerSessionView.Mode(variants: DrillVariant.allCases.filter(picked.contains),
                                language: language,
                                phraseSource: phraseDrill?.source,
                                templates: phraseDrill?.templates ?? [],
                                modifiers: modifiers)
    }

    func start() {
        launch = Launch(mode: buildMode())
    }

    // MARK: - The ladder

    /// Reads every variant's stored rung at once, because a requirement names a
    /// variant other than the row it gates (Phrases is bought with Clock).
    func reloadProgress() {
        var levels: [DrillVariant: Int] = [:]
        for variant in DrillVariant.allCases {
            levels[variant] = TrainerProgress.best(for: "\(variant.storageTag).\(language)")
        }
        #if DEBUG
        levels.merge(Self.uitestProgress) { _, seeded in seeded }
        #endif
        progress = levels
        #if DEBUG
        if launch == nil, UserDefaults.standard.bool(forKey: "uitest-run") { start() }
        #endif
    }

    // MARK: - Chrome

    var languageName: String {
        LanguageNames.display(language, locale: locale, catalog: model.catalog)
    }

    func heading(_ key: LocalizedStringKey) -> some View {
        Text(key)
            .font(DL.Fonts.title)
            .foregroundStyle(Color.dlTextPrimary)
            .accessibilityAddTraits(.isHeader)
    }
}

#if DEBUG
extension NumbersOverview {
    /// `-uitest-progress Numbers=7,Forms=5` stands the ladder at a rung a
    /// screenshot cannot climb to by thumb. In MEMORY only: a photographed
    /// unlock must never become a stored one.
    static var uitestProgress: [DrillVariant: Int] {
        let known: [String: DrillVariant] = ["numbers": .numbers, "clock": .clock,
                                             "phrases": .phrases, "forms": .forms]
        let pairs = (UserDefaults.standard.string(forKey: "uitest-progress") ?? "")
            .split(separator: ",")
            .compactMap { entry -> (DrillVariant, Int)? in
                let parts = entry.split(separator: "=")
                guard parts.count == 2,
                      let variant = known[parts[0].trimmingCharacters(in: .whitespaces).lowercased()],
                      let level = Int(parts[1].trimmingCharacters(in: .whitespaces))
                else { return nil }
                return (variant, level)
            }
        return Dictionary(pairs) { _, last in last }
    }
}
#endif
