import SwiftUI
import SprossKern

/// The Numbers hub entry: a numbers page for the language being learned, and
/// the place its drill is started from.
///
/// Three sections, start first: the run to practice with (what it asks, how it
/// is played, the button), then what this language does with numbers (a table
/// generated by kern, never authored) and the handful of things that trip a
/// learner up. Why that order, and what the page stores: `docs/drills.md`.
///
/// The rows and toggles live in NumbersOverview+Practice.swift, the table and
/// the notes in NumbersOverview+Reference.swift; split purely for file size.
struct NumbersOverview: View {
    let model: AppModel
    /// The language being learned: what the table describes, and what the run
    /// is answered in.
    let language: String
    /// The frames a sentence run would draw from and the side they are prompted
    /// from — nil where the pair realizes none, and then Phrases is not offered.
    let phraseDrill: (source: String, templates: [PhraseTemplate])?

    /// The highest Sprosse ever reached per exercise in THIS language — the one
    /// source the unlock ladder reads. Held in state rather than read per row so
    /// a run that just booked a Sprosse refreshes the whole ladder in one place.
    // why: internal, not private — +Practice.swift renders the ladder from it.
    @State var progress: [NumbersExercise: Int] = [:]
    /// Never empty in practice; `Los` is disabled while it is. A list, in
    /// kern's own order — `DrillSelection` hands it back ordered, so the same
    /// state collapses the same way on both platforms.
    @State var picked: [NumbersExercise] = [.counting]
    @State var modifiers: Set<DrillModifier> = []
    // why: internal, not private — +Challenge.swift launches a challenge through it.
    @State var launch: DrillLaunch<NumbersLaunch>?
    /// The code the learner is typing into the challenge section.
    @State var challengeCode = ""
    /// Why the last code could not be accepted; nil until one is refused.
    @State var challengeRefusal: Text?
    /// What the run that just closed came to. Shown as one tile above the picks
    /// instead of a screen of its own — three figures do not earn a page, and a
    /// page they do not earn is one more ✕ before the next run.
    // why: internal, not private — the DEBUG hook seeds it for screenshots.
    @State var lastRun: DrillRunResult?
    /// The rows this page last showed padlocked and now shows open — marked
    /// once (`DrillUnlockMark`), then filed as seen.
    // why: internal, not private — +Practice.swift marks the rows from it.
    @State var unlocking: Set<String> = []
    @Environment(\.locale) private var locale

    var body: some View {
        DrillOverviewPage(title: Text("numbers.title \(languageName)"),
                          lastRun: lastRun,
                          startable: !picked.isEmpty,
                          start: start,
                          // why: the table is twenty screens long — `center` is the
                          // only way to photograph a middle band, which is where the
                          // readings get long enough to test the wrap.
                          scrollAnchor: DrillUITest.anchor(["table": .center, "notes": .bottom])) {
            practiceSection
            // why: challenges are timed, which screen reader users are spared.
            if !AutoAdvance.screenReaderOn { challengeSection }
            referenceSection
            notesSection
        }
        .onAppear { reloadProgress() }
        // why: a closing run books its best Sprossen into TrainerProgress, so the
        // ladder behind it is stale the moment the cover comes down.
        .fullScreenCover(item: $launch, onDismiss: reloadProgress) { launch in
            NumbersRunView(mode: launch.value.mode, challenge: launch.value.challenge,
                           normalizer: launch.value.mode.normalizer(model),
                               catalog: model.catalog, model: model,
                               onFinish: { result in
                                   withAnimation(.easeOut(duration: 0.25)) { lastRun = result }
                               })
                .environment(\.locale, model.knownLocale)
        }
    }

    // MARK: - Starting a run

    /// The run the current picks describe. Phrase frames ride along whether or
    /// not Phrases is picked — `Mode` drops a frameless Phrases itself, and
    /// carrying them means the run samples from the set the screen was opened with.
    func buildMode() -> NumbersRunView.Mode {
        NumbersRunView.Mode(exercises: picked,
                                language: language,
                                phraseSource: phraseDrill?.source,
                                templates: phraseDrill?.templates ?? [],
                                modifiers: modifiers)
    }

    func start() {
        launch = DrillLaunch(value: NumbersLaunch(mode: buildMode()))
    }

    // MARK: - The ladder

    /// Reads every exercise's stored Sprosse at once, because a requirement names
    /// an exercise other than the row it gates (Phrases is bought with Clock).
    func reloadProgress() {
        var levels: [NumbersExercise: Int] = [:]
        for exercise in NumbersExercise.allCases {
            levels[exercise] = TrainerProgress.best(
                for: NumbersMode.companion.progressKey(exercise: exercise, language: language))
        }
        #if DEBUG
        levels.merge(Self.uitestProgress) { _, seeded in seeded }
        #endif
        progress = levels
        normalizePicks()
        markUnlocks()
        DrillUITest.autoStart("numbers", ready: launch == nil, start: start)
    }

    // MARK: - Chrome

    var languageName: String {
        LanguageNames.display(language, catalog: model.catalog)
    }
}

/// What a start tap opens: the picked run, or a challenge.
struct NumbersLaunch {
    let mode: NumbersMode
    var challenge: NumbersChallenge?
}

#if DEBUG
extension NumbersOverview {
    /// `-uitest-progress Numbers=7,Forms=5` stands the ladder at a Sprosse a
    /// screenshot cannot climb to by thumb. In MEMORY only: a photographed
    /// unlock must never become a stored one.
    static var uitestProgress: [NumbersExercise: Int] {
        let known: [String: NumbersExercise] = ["numbers": .counting, "clock": .clock,
                                             "phrases": .phrases, "forms": .forms]
        let pairs = (UserDefaults.standard.string(forKey: "uitest-progress") ?? "")
            .split(separator: ",")
            .compactMap { entry -> (NumbersExercise, Int)? in
                let parts = entry.split(separator: "=")
                guard parts.count == 2,
                      let exercise = known[parts[0].trimmingCharacters(in: .whitespaces).lowercased()],
                      let level = Int(parts[1].trimmingCharacters(in: .whitespaces))
                else { return nil }
                return (exercise, level)
            }
        return Dictionary(pairs) { _, last in last }
    }
}
#endif

// MARK: - Unlocks, marked once

extension NumbersOverview {

    /// Every row that can wear a padlock, with its kern name and its title.
    private var padlockable: [(row: String, open: Bool, title: String)] {
        let exercises = DrillSelection.shared
            .offered(language: language, phrasesRealized: phraseDrill != nil)
            .map { (DrillUnlockMark.shared.row(exercise: $0), unlocked($0), $0.trainerTitleName) }
        let modifiers = DrillModifier.allCases
            .map { (DrillUnlockMark.shared.row(modifier: $0), unlocked($0), $0.trainerTitleName) }
        return exercises + modifiers
    }

    /// Compares what the page shows padlocked with what it last showed, and
    /// says what just opened.
    func markUnlocks() {
        let rows = padlockable
        let marked = TrainerProgress.unlockMarks(
            page: DrillUnlockMark.shared.numbersPage(language: language),
            locked: Set(rows.filter { !$0.open }.map(\.row)),
            open: Set(rows.filter(\.open).map(\.row)))
        guard !marked.isEmpty else { return }
        unlocking.formUnion(marked)
        UnlockMark.announce(rows.filter { marked.contains($0.row) }
                                .map { ChromeStrings.string($0.title, locale: locale) },
                            locale: locale)
    }
}
