package net.spross.kern.catalog

import net.spross.kern.model.Language
import net.spross.kern.trainer.Trainer

/**
 * What the drills read out of the catalog: the atlas and the calendars joined for one
 * profile, and the prose that heads their reference pages.
 *
 * File presence IS the registry throughout — adding a language's atlas names or calendar
 * is dropping a file, and no code lists which languages have one.
 */

/**
 * The atlas joined for one profile, or null where this pair has no drill at all: no
 * manifest, a side with no `countries/<lang>.json`, or a join neither side realizes.
 * File presence IS the registry, exactly as [alphabet]'s is.
 *
 * Rows only survive where BOTH sides name them, so nothing downstream has to ask
 * whether a name exists — and the tiers come out EFFECTIVE, with the profile's own
 * languages and their countries lowered to 1 ([CountryAtlas]).
 */
fun Catalog.countryDrillContent(source: Language, target: Language): CountryDrillContent? {
    require(source != target) { "source == target ($source)" }
    val atlas = countryAtlas ?: return null
    val sourceNames = countryNames[source] ?: return null
    val targetNames = countryNames[target] ?: return null
    val profile = setOf(source, target)
    val joinedLanguages = atlas.languages.mapNotNull { row ->
        AtlasLanguageEntry(
            code = row.code,
            tier = if (row.code in profile) 1 else row.tier,
            source = languageName(source, row.code) ?: return@mapNotNull null,
            target = languageName(target, row.code) ?: return@mapNotNull null,
        )
    }
    val joinedCountries = atlas.countries.mapNotNull { row ->
        AtlasCountryEntry(
            slug = row.slug,
            flag = row.flag,
            tier = if (row.languages.any { it in profile }) 1 else row.tier,
            languages = row.languages,
            source = sourceNames[row.slug] ?: return@mapNotNull null,
            target = targetNames[row.slug] ?: return@mapNotNull null,
        )
    }
    if (joinedCountries.isEmpty()) return null
    return CountryDrillContent(source, target, joinedCountries, joinedLanguages)
}

/**
 * The calendar authored for [lang], null where no file is authored. File presence IS
 * the registry, exactly as [alphabet]'s is — adding a language's calendar is dropping
 * a file, and no code lists which languages have one.
 */
fun Catalog.dateNames(lang: Language): DateCalendar? = dateCalendars[lang]

/**
 * The two calendars joined for one profile, or null where this pair has no drill:
 * a side with no `dates/<lang>.json`, or a target the trainer cannot read days for.
 *
 * The day of the month is GENERATED by the answer language's pack and never authored,
 * so a language without one can still supply prompts and never answers — the frame
 * rule ([Catalog.phraseTemplates]), for the frame's reason. Both calendars carry the full
 * seven and twelve by parse, so the join is total and nothing downstream asks whether
 * a name exists.
 */
fun Catalog.dateDrillContent(source: Language, target: Language): DateDrillContent? {
    require(source != target) { "source == target ($source)" }
    val sourceCalendar = dateCalendars[source] ?: return null
    val targetCalendar = dateCalendars[target] ?: return null
    if (!Trainer.supports(target)) return null
    return DateDrillContent(
        source = source,
        target = target,
        weekdays = sourceCalendar.weekdays.mapIndexed { i, name ->
            DateEntry(i, name, targetCalendar.weekdays[i])
        },
        months = sourceCalendar.months.mapIndexed { i, name ->
            DateEntry(i, name, targetCalendar.months[i])
        },
        numeric = sourceCalendar.numeric,
        patterns = targetCalendar.patterns,
    )
}

/**
 * What trips a learner up in [language]'s numbers — authored prose from
 * `phrases/<lang>.json`, keyed by explanation language exactly as a realization's notes
 * are, and selected here by whoever is READING.
 *
 * Unlike a realization note it does fall back to [Catalog.FALLBACK_SOURCE]: a note hangs off a
 * card that carries itself without it, while this IS the section, and a reference page
 * a learner can read in English beats a heading with nothing under it. Empty where the
 * language authors none at all.
 */
fun Catalog.numberNotes(language: Language, reader: Language): List<String> {
    val byReader = drillNotes[language] ?: return emptyList()
    return byReader[reader] ?: byReader[Catalog.FALLBACK_SOURCE].orEmpty()
}

/** [numberNotes] for the calendar, out of `dates/<lang>.json`'s own `dateNotes`. */
fun Catalog.dateNotes(language: Language, reader: Language): List<String> {
    val byReader = dateCalendars[language]?.notes ?: return emptyList()
    return byReader[reader] ?: byReader[Catalog.FALLBACK_SOURCE].orEmpty()
}
