package net.spross.kern.catalog

import net.spross.kern.model.Language

/**
 * One language's calendar: `catalog/dates/<lang>.json`, the dates drill's own content.
 *
 * Unlike the atlas there is no manifest half — seven weekdays and twelve months in ISO
 * order are the same list in every language, so the per-language file is the whole of it
 * and **file presence is the registry**, exactly as the alphabet's is.
 *
 * The day of the month is deliberately absent: it is a NUMERAL, generated by the
 * language's trainer pack (`docs/date-readings.md`), because a second table of thirty-one
 * ordinals per language would be the same fact in two homes.
 */
data class DateCalendar(
    val language: Language,
    /** Exactly seven, Monday first — every one carrying its [DateNames.abbr]. */
    val weekdays: List<DateNames>,
    /** Exactly twelve, January first. */
    val months: List<DateNames>,
    /** How this language writes a date in digits, over `{d}`/`{m}`/`{y}` — display only. */
    val numeric: String,
    val patterns: DatePatterns,
)

/** One calendar name, on the realization schema: a synonym is taught, a variant only accepted. */
data class DateNames(
    val text: String,
    /** Distinct lexemes for the same day or month (de `Sonnabend`), prompt-worthy. */
    val synonyms: List<String> = emptyList(),
    /** Accept-only spellings, never displayed (eo's x-system twins). */
    val variants: List<String> = emptyList(),
    /** Weekdays only — the short form the PROMPT wears in a dated line (`Mo, 3.3.`). */
    val abbr: String? = null,
    /**
     * The form this word takes INSIDE a date where that differs from [text] — uk `березня`
     * against the nominative `березень` a bare-name answer is. Named for the rule, not for
     * the case, so a language whose date takes some other form needs no second key.
     */
    val dateForm: String? = null,
    /** Keyed by explanation language, exactly as a realization's notes are. */
    val notes: Map<Language, String> = emptyMap(),
)

/**
 * How this language assembles a date, over `{weekday}`, `{day}`, `{month}` and `{year}`.
 * [dateWithYear] is optional: a language that reads no year inside a date omits it and its
 * ladder simply stops one Sprosse short (uk, `docs/date-readings.md`).
 */
data class DatePatterns(
    val dayMonth: DatePattern,
    val date: DatePattern,
    val dateWithYear: DatePattern?,
)

/**
 * One assembly pattern, on the realization schema the calendar names already wear:
 * a [synonyms] entry is a second way the language genuinely SAYS the date and takes its
 * turn on the reveal (en `the third of March` beside `March third`), a [variants] entry is
 * only ever accepted (the article that same order drops in speech).
 */
data class DatePattern(
    val text: String,
    val synonyms: List<String> = emptyList(),
    val variants: List<String> = emptyList(),
) {
    /** Every assembly that grades, the taught ones first. */
    val forms: List<String> get() = taught + variants

    /** The assemblies a reveal may teach. */
    val taught: List<String> get() = listOf(text) + synonyms
}

/**
 * The calendars joined for one (source, target) profile — everything the drill grades
 * against, and everything the reference table renders, from the same rows.
 *
 * Both sides' names stand side by side on every row, so a caller never has to ask whether
 * a name exists. The two halves that are NOT symmetric are named for the side that owns
 * them: [numeric] is the prompt language's digits and [patterns] the answer language's
 * assembly, because the source contributes only its weekday abbreviation and its numeric
 * format while the answer side spells the whole date out.
 */
data class DateDrillContent(
    val source: Language,
    val target: Language,
    /** Seven, Monday first. */
    val weekdays: List<DateEntry>,
    /** Twelve, January first. */
    val months: List<DateEntry>,
    /** The SOURCE's digit format — what a dated prompt is written in, never graded. */
    val numeric: String,
    /** The TARGET's assembly — what an answer is spelled out with. */
    val patterns: DatePatterns,
)

/** One weekday or month as both sides call it; [index] is 0-based in ISO order. */
data class DateEntry(
    val index: Int,
    val source: DateNames,
    val target: DateNames,
)
