import Foundation
import Testing
@testable import DuoKern

/// Golden-vector equality against Fixtures/trainer-golden.json,
/// generated by running the prototype's extracted JS functions with node
/// (scratchpad golden.mjs) — expected strings were not hand-derived.
struct TrainerGoldenTests {

    struct Fixture: Decodable {
        struct GermanYear: Decodable { let display: String; let accepted: [String] }
        struct GermanClockEntry: Decodable { let standard: String; let regional: String }
        let germanNumbers: [String: String]
        let swahiliNumbers: [String: String]
        let germanYears: [String: GermanYear]
        let swahiliYears: [String: String]
        let germanClock: [String: GermanClockEntry]
        let swahiliClock: [String: String]
    }

    static func load() throws -> Fixture {
        let url = try #require(Bundle.module.url(forResource: "trainer-golden", withExtension: "json",
                                                 subdirectory: "Fixtures"))
        return try JSONDecoder().decode(Fixture.self, from: Data(contentsOf: url))
    }

    static func parseClock(_ key: String) throws -> (h: Int, m: Int) {
        let parts = key.split(separator: ":")
        return (try #require(Int(parts[0])), try #require(Int(parts[1])))
    }

    @Test func germanNumbersMatchGolden() throws {
        let fixture = try Self.load()
        #expect(fixture.germanNumbers.count == 38)
        for (key, expected) in fixture.germanNumbers {
            let task = Trainer.number(try #require(Int(key)), language: .german)
            #expect(task.display == expected, "n=\(key)")
            #expect(task.accepted == [expected], "n=\(key)")
            #expect(task.prompt == key)
        }
    }

    @Test func swahiliNumbersMatchGolden() throws {
        let fixture = try Self.load()
        #expect(fixture.swahiliNumbers.count == 38)
        for (key, expected) in fixture.swahiliNumbers {
            let task = Trainer.number(try #require(Int(key)), language: .swahili)
            #expect(task.display == expected, "n=\(key)")
            #expect(task.accepted == [expected], "n=\(key)")
        }
    }

    @Test func germanYearsMatchGolden() throws {
        let fixture = try Self.load()
        #expect(fixture.germanYears.count == 10)
        for (key, expected) in fixture.germanYears {
            let task = Trainer.year(try #require(Int(key)), language: .german)
            #expect(task.display == expected.display, "y=\(key)")
            #expect(task.accepted == expected.accepted, "y=\(key)")
        }
    }

    @Test func swahiliYearsArePlainCardinalReadings() throws {
        let fixture = try Self.load()
        for (key, expected) in fixture.swahiliYears {
            let task = Trainer.year(try #require(Int(key)), language: .swahili)
            #expect(task.display == expected, "y=\(key)")
            #expect(task.accepted == [expected], "y=\(key)")
        }
    }

    @Test func germanClockMatchesGolden() throws {
        let fixture = try Self.load()
        #expect(fixture.germanClock.count == 120)
        for (key, expected) in fixture.germanClock {
            let (h, m) = try Self.parseClock(key)
            let task = Trainer.clock(hour: h, minute: m, language: .german)
            #expect(task.prompt == key)
            #expect(task.display == expected.standard, "t=\(key)")
            var accepted = [expected.standard]
            if expected.regional != expected.standard { accepted.append(expected.regional) }
            #expect(task.accepted == accepted, "t=\(key)")
        }
    }

    @Test func swahiliClockMatchesGolden() throws {
        let fixture = try Self.load()
        #expect(fixture.swahiliClock.count == 120)
        for (key, expected) in fixture.swahiliClock {
            let (h, m) = try Self.parseClock(key)
            let task = Trainer.clock(hour: h, minute: m, language: .swahili)
            #expect(task.display == expected, "t=\(key)")
            #expect(task.accepted == [expected], "t=\(key)")
            #expect(task.gloss?.contains("Saa") == true)
        }
    }
}
