package net.spross.app.ui

import androidx.activity.compose.BackHandler
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.rememberScrollState
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import net.spross.app.AppModel
import net.spross.app.Chrome
import net.spross.app.badge
import net.spross.app.bestSprosse
import net.spross.app.hint
import net.spross.app.name
import net.spross.app.speakFormOnTap
import net.spross.app.unlockPrice
import net.spross.kern.trainer.DrillModifier
import net.spross.kern.trainer.DrillSelection
import net.spross.kern.trainer.DrillUnlocks
import net.spross.kern.trainer.DrillVariant
import net.spross.kern.trainer.TrainerMode

/**
 * The Numbers entry: a numbers page for the language being learnt, and the place its drill
 * is started from.
 *
 * Three sections, start first: the run to practice with (what it asks, how it is played,
 * the button), then what this language does with numbers — a table GENERATED by kern from
 * the packs the drill grades against — and the handful of things that trip a learner up.
 * Why that order, and what the page stores: `docs/surfaces.md`.
 */
@Composable
fun NumbersOverviewScreen(model: AppModel) {
    val chrome = model.chrome
    val stamp = model.box?.joinStamp ?: return
    val language = stamp.target
    val scroll = rememberScrollState()
    BackHandler { model.closeOverview() }

    // Carried whether or not Phrases is picked: kern drops a frameless Phrases itself, and
    // carrying them means the run samples the set the page was opened with.
    val templates = remember(stamp) {
        model.catalog?.phraseTemplates(stamp.source, language).orEmpty()
    }
    val offered = remember(language, templates) {
        DrillSelection.offered(language, phrasesRealized = templates.isNotEmpty())
    }
    val ladder = model.trainer.ladder
    val combining = DrillSelection.combining(offered, ladder)

    // Names rather than the enums, so a rotation keeps the picks: only primitives survive
    // a saved instance state.
    // layer-ok: the picker's opening preference, which `normalized` below still collapses
    var pickedNames by rememberSaveable { mutableStateOf(listOf(DrillVariant.Numbers.name)) }
    var modifierNames by rememberSaveable { mutableStateOf(emptyList<String>()) }
    val picked = DrillSelection.normalized(
        picked = pickedNames.mapNotNull { name -> DrillVariant.entries.find { it.name == name } },
        offered = offered,
        progress = ladder,
    )
    val modifiers = modifierNames
        .mapNotNull { name -> DrillModifier.entries.find { it.name == name } }
        .filter { DrillUnlocks.unlocked(it, ladder) }
        .toSet()

    val result = model.trainer.result
    // why: a tile inserted ABOVE the content keeps the scroll offset, so what a run came
    // back with would sit off the top of a page the learner is still looking at.
    LaunchedEffect(result) { if (result != null) scroll.animateScrollTo(0) }

    val start = {
        model.startTrainerRun(
            TrainerMode(
                selection = picked,
                language = language,
                // The live quirk kern documents: the source rides along whenever the pair
                // realizes frames, which is what the standing record keys are already
                // written under.
                phraseSource = if (templates.isEmpty()) null else stamp.source,
                templates = templates,
                modifiers = modifiers,
            ),
        )
    }

    OverviewScaffold(
        title = chrome.numbersTitle.format(model.languageName(language)),
        chrome = chrome,
        scroll = scroll,
        startEnabled = picked.isNotEmpty(),
        onClose = { model.closeOverview() },
        onStart = start,
    ) {
        result?.let { DrillResultTile(it, model.trainer.resultTitle, chrome) }

        OverviewHeading(chrome.trainerOverviewPractice)
        Column(verticalArrangement = Arrangement.spacedBy(Theme.spacing.sm)) {
            for (variant in offered) {
                VariantRow(variant, chrome, ladder, combining, variant in picked) {
                    pickedNames = DrillSelection
                        .toggled(picked, variant, combining)
                        .map { it.name }
                }
            }
            if (!combining) OverviewNote(chrome.numbersCombineLocked)
        }
        OverviewPanel {
            for (modifier in DrillModifier.entries) {
                ModifierRow(modifier, chrome, ladder, modifier in modifiers) { on ->
                    modifierNames = if (on) {
                        modifierNames + modifier.name
                    } else {
                        modifierNames - modifier.name
                    }
                }
            }
        }
        OverviewStartButton(chrome, picked.isNotEmpty(), start)

        OverviewHeading(chrome.numbersReference)
        NumberReferenceTable(language, chrome, speak = { model.speakFormOnTap(it, language) })

        val notes = remember(stamp) {
            model.catalog?.numberNotes(language, stamp.source).orEmpty()
        }
        if (notes.isNotEmpty()) {
            OverviewHeading(chrome.numbersNotes)
            OverviewPanel {
                for (note in notes) {
                    Text(note, style = MaterialTheme.typography.bodyMedium)
                }
            }
        }
    }
}

/**
 * One exercise the run may ask. A variant the pair cannot offer at all has no row — this is
 * only ever handed the offered ones — and a locked one keeps its row and states its price
 * out of kern's own unlock table.
 */
@Composable
private fun VariantRow(
    variant: DrillVariant,
    chrome: Chrome,
    ladder: Map<DrillVariant, Int>,
    combining: Boolean,
    selected: Boolean,
    onTap: () -> Unit,
) {
    val open = DrillUnlocks.unlocked(variant, ladder)
    SelectionRow(
        title = chrome.badge(variant),
        caption = when {
            !open -> chrome.unlockPrice(DrillUnlocks.requirements(variant))
            // The Sprosse it has reached, where a run has booked one — nothing until then.
            (ladder[variant] ?: 0) > 0 -> chrome.bestSprosse(variant, ladder.getValue(variant))
            else -> null
        },
        mark = when {
            !open -> RowMark.Locked
            combining -> RowMark.Many
            else -> RowMark.One
        },
        selected = open && selected,
        onClick = onTap,
    )
}

/**
 * How the run is played, in the shared modifier row: the price comes out of kern's own
 * unlock table, and the row itself is the one the atlas page wears too.
 */
@Composable
private fun ModifierRow(
    modifier: DrillModifier,
    chrome: Chrome,
    ladder: Map<DrillVariant, Int>,
    on: Boolean,
    onChange: (Boolean) -> Unit,
) {
    val open = DrillUnlocks.unlocked(modifier, ladder)
    ModifierSwitchRow(
        title = chrome.name(modifier),
        caption = if (open) chrome.hint(modifier) else chrome.unlockPrice(DrillUnlocks.requirements(modifier)),
        open = open,
        on = on,
        onChange = onChange,
    )
}
