package net.spross.app.ui

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import net.spross.app.AppModel
import net.spross.app.Chrome
import net.spross.app.badge
import net.spross.app.bestSprosse
import net.spross.app.hint
import net.spross.app.name
import net.spross.app.speakFormOnTap
import net.spross.app.startTrainerRun
import net.spross.app.unlockPrice
import net.spross.kern.catalog.numberNotes
import net.spross.kern.trainer.DrillModifier
import net.spross.kern.trainer.DrillSelection
import net.spross.kern.trainer.DrillUnlockMark
import net.spross.kern.trainer.DrillUnlocks
import net.spross.kern.trainer.NumbersExercise
import net.spross.kern.trainer.NumbersMode

/**
 * The Numbers entry: a numbers page for the language being learned, and the place its drill
 * is started from.
 *
 * Three sections, start first: the run to practice with (what it asks, how it is played,
 * the button), then what this language does with numbers — a table GENERATED by kern from
 * the packs the drill grades against — and the handful of things that trip a learner up.
 * Why that order, and what the page stores: `docs/drills.md`.
 */
@Composable
fun NumbersOverviewScreen(model: AppModel) {
    val chrome = model.chrome
    val stamp = model.box?.joinStamp ?: return
    val language = stamp.target
    // Carried whether or not Phrases is picked: kern drops a frameless Phrases itself, and
    // carrying them means the run samples the set the page was opened with.
    val templates = remember(stamp) {
        model.catalog?.phraseTemplates(stamp.source, language).orEmpty()
    }
    val offered = remember(language, templates) {
        DrillSelection.offered(language, phrasesRealized = templates.isNotEmpty())
    }
    val ladder = model.trainer.ladder
    val combining = DrillSelection.combining(offered, ladder)

    // Names rather than the enums, so a rotation keeps the picks: only primitives survive
    // a saved instance state.
    // layer-ok: the picker's opening preference, which `normalized` below still collapses
    var pickedNames by rememberSaveable { mutableStateOf(listOf(NumbersExercise.Counting.name)) }
    var modifierNames by rememberSaveable { mutableStateOf(emptyList<String>()) }
    val picked = DrillSelection.normalized(
        picked = pickedNames.mapNotNull { name -> NumbersExercise.entries.find { it.name == name } },
        offered = offered,
        progress = ladder,
    )
    val modifiers = modifierNames
        .mapNotNull { name -> DrillModifier.entries.find { it.name == name } }
        .filter { DrillUnlocks.unlocked(it, ladder) }
        .toSet()

    val picks = NumbersMode(
        selection = picked,
        language = language,
        // The live quirk kern documents: the source rides along whenever the pair
        // realizes frames, which is what the standing record keys are already
        // written under.
        phraseSource = if (templates.isEmpty()) null else stamp.source,
        templates = templates,
        modifiers = modifiers,
    )
    val start = { model.startTrainerRun(picks) }

    // An unlock is marked once: kern compares what the page shows padlocked with what it last did.
    val rows = offered.map { DrillUnlockMark.row(it) to DrillUnlocks.unlocked(it, ladder) } +
        DrillModifier.entries.map { DrillUnlockMark.row(it) to DrillUnlocks.unlocked(it, ladder) }
    val locked = rows.filter { !it.second }.map { it.first }.toSet()
    val unlocking = remember(language, locked) {
        model.trainer.store.unlockMarks(
            DrillUnlockMark.numbersPage(language),
            locked,
            rows.filter { it.second }.map { it.first }.toSet(),
        )
    }
    AnnounceUnlocks(
        offered.filter { DrillUnlockMark.row(it) in unlocking }.map { chrome.name(it) } +
            DrillModifier.entries.filter { DrillUnlockMark.row(it) in unlocking }.map { chrome.name(it) },
        chrome,
    )

    OverviewScaffold(
        model = model,
        title = chrome.numbersTitle.format(model.languageName(language)),
        startEnabled = picked.isNotEmpty(),
        onStart = start,
    ) {
        Column(verticalArrangement = Arrangement.spacedBy(Theme.spacing.sm)) {
            for (exercise in offered) {
                ExerciseRow(exercise, chrome, ladder, combining, exercise in picked, DrillUnlockMark.row(exercise) in unlocking) {
                    pickedNames = DrillSelection
                        .toggled(picked, exercise, combining)
                        .map { it.name }
                }
            }
            if (!combining) OverviewNote(chrome.numbersCombineLocked)
        }
        Panel {
            // why: timed runs are hidden from screen reader users.
            val playable = DrillModifier.entries.filter {
                it != DrillModifier.Timed || !model.pronouncer.readsScreenAloud
            }
            for (modifier in playable) {
                ModifierRow(modifier, chrome, ladder, modifier in modifiers, DrillUnlockMark.row(modifier) in unlocking) { on ->
                    modifierNames = if (on) {
                        modifierNames + modifier.name
                    } else {
                        modifierNames - modifier.name
                    }
                }
            }
        }
        OverviewStartButton(chrome, picked.isNotEmpty(), start)
        // why: challenges are timed, which screen reader users are spared.
        if (!model.pronouncer.readsScreenAloud) NumbersChallengeSection(model, picks)

        OverviewHeading(chrome.numbersReference)
        NumberReferenceTable(language, chrome, speak = { model.speakFormOnTap(it, language) })

        val notes = remember(stamp) {
            model.catalog?.numberNotes(language, stamp.source).orEmpty()
        }
        ReferenceNotes(notes, chrome)
    }
}

/**
 * One exercise the run may ask. An exercise the pair cannot offer at all has no row — this is
 * only ever handed the offered ones — and a locked one keeps its row and states its price
 * out of kern's own unlock table.
 */
@Composable
private fun ExerciseRow(
    exercise: NumbersExercise,
    chrome: Chrome,
    ladder: Map<NumbersExercise, Int>,
    combining: Boolean,
    selected: Boolean,
    unlocking: Boolean,
    onTap: () -> Unit,
) {
    val open = DrillUnlocks.unlocked(exercise, ladder)
    SelectionRow(
        title = chrome.badge(exercise),
        caption = when {
            !open -> chrome.unlockPrice(DrillUnlocks.requirements(exercise))
            // The Sprosse it has reached, where a run has booked one — nothing until then.
            (ladder[exercise] ?: 0) > 0 -> chrome.bestSprosse(exercise, ladder.getValue(exercise))
            else -> null
        },
        mark = when {
            !open -> RowMark.Locked
            combining -> RowMark.Many
            else -> RowMark.One
        },
        selected = open && selected,
        unlocking = unlocking,
        onClick = onTap,
    )
}

/**
 * How the run is played, in the shared modifier row: the price comes out of kern's own
 * unlock table, and the row itself is the one the atlas page wears too.
 */
@Composable
private fun ModifierRow(
    modifier: DrillModifier,
    chrome: Chrome,
    ladder: Map<NumbersExercise, Int>,
    on: Boolean,
    unlocking: Boolean,
    onChange: (Boolean) -> Unit,
) {
    val open = DrillUnlocks.unlocked(modifier, ladder)
    ModifierSwitchRow(
        title = chrome.name(modifier),
        caption = if (open) chrome.hint(modifier) else chrome.unlockPrice(DrillUnlocks.requirements(modifier)),
        open = open,
        on = on,
        unlocking = unlocking,
        onChange = onChange,
    )
}
