package net.spross.app

/**
 * The German chrome table. Wording follows the iOS String Catalog
 * (`App/Sources/Resources/Localizable.xcstrings`) key for key, so a learner meeting the
 * same surface on either platform reads the same sentence.
 */
internal val ChromeDe = Chrome(
    heuteTitle = "Heute",
    practice = "Üben",
    extraRound = "Extra-Runde",
    doneToday = "Für heute geschafft!",
    emptyState = "Die Box wächst, während dein Material sitzt.",
    dueLabel = "fällig",
    newLabel = "neu",
    consolidatedLabel = "gefestigt",
    freshLabel = "frisch",
    changeLanguages = "Sprachen ändern",
    chooseTitle = "Was möchtest du lernen?",
    iSpeak = "Ich spreche",
    iLearn = "Ich lerne",
    conceptsSuffix = "Begriffe",
    letsGo = "Los geht's",
    backLabel = "Zurück",
    check = "Prüfen",
    reveal = "Aufdecken",
    next = "Weiter",
    alsoPrefix = "auch:",
    typoNote = "Kleiner Tippfehler – zählt!",
    otherWordNote = "Übrigens: %1\$s heißt „%2\$s“",
    answerPlaceholder = "In %s …",
    again = "Nochmal",
    hard = "Schwer",
    good = "Gut",
    easy = "Leicht",
    sessionDone = "Geschafft!",
    summaryLine = "%d neu · %d gefestigt · %d wiederholt",
    keepPracticing = "Weiter üben",
    finish = "Fertig",
    pluralEquals = "= Pl.",
    pluralOnly = "nur Pl.",
    pluralPrefix = "Pl. ",
    readAloud = "Aussprache vorlesen",
    stateOn = "an",
    stateOff = "aus",
    pronounce = "Aussprechen",
    aboutButton = "Info",
    audioToggle = "Wörter vorlesen",
    audioToggleHint = "Wörter beim Üben automatisch vorlesen. Tippen auf ein Wort " +
        "spricht es erneut — auch bei ausgeschaltetem Vorlesen.",
    creditsTitle = "Sprecher & Lizenzen",
    creditsRecordings = "%d Aufnahmen",
    creditsUnmodified = "Aufnahmen unverändert übernommen",
    creditsCommons = "Aufnahmen von Wikimedia Commons",
    trainingTitle = "Training",
    lettersTitle = "Buchstaben",
    lettersHear = "Welcher Buchstabe ist das?",
    lettersSpell = "Was fehlt im Wort?",
    lettersDictation = "Schreib, was du hörst",
    letterChoice = "Buchstabe %s",
    replayPrompt = "Noch einmal anhören",
    promptInLanguage = "auf %s",
    level = "Stufe %d",
    streak = "🔥 %d in Folge",
    typoCorrection = "Fast! Richtig geschrieben: %s",
    heardInstead = "Gehört war: %s",
    audioOff = "Ton ist aus",
    enableSound = "Ton einschalten",
    tasksDone = "%d Aufgaben 🎯",
    bestStreak = "Beste Serie: 🔥 %d in Folge",
    answerCorrect = "Richtig",
    answerWrong = "Falsch",
    correctAnswer = "Richtig: %s",

    boxTitle = "Die Box",
    boxNav = "Box",
    boxSubtitle = "%1\$d von %2\$d Karten in Arbeit",
    ownWordsTitle = "Eigene Wörter",
    ownWordsExplainer = "Eigene Wörter stehen in ihrem eigenen Bereich. " +
        "Ein wachsender Katalog rührt sie nicht an.",
    packArea = "Pack in die Box (%d)",
    packDone = "Alles eingepackt",
    packWord = "Dieses Wort einpacken",
    packedWord = "Eingepackt",
    suspended = "Pausiert",
    wake = "Wecken",
    phrasesLocked = "%d Sätze",
    phaseLearning = "Lernt",
    phaseReview = "Sitzt",
    phaseRelearning = "Wackelt",

    search = "Suchen",
    searchPlaceholder = "Wort oder Bereich",
    searchHint = "Wörter beider Sprachen und die Namen der Bereiche.",
    searchAreas = "Bereiche",
    searchWords = "Wörter",
    searchNothing = "Nichts zu „%s“ in der Box.",
    searchWriteOwn = "„%s“ selbst eintragen",
    searchClear = "Suche löschen",

    ownWordTitle = "Eigenes Wort",
    ownWordInLanguage = "Auf %s",
    ownWordPicture = "Bild (optional)",
    ownWordAdd = "Anlegen",
    ownWordRemove = "Wort löschen",

    settingsTitle = "Einstellungen",
    profileHint = "Beim Wechsel der Ausgangssprache bleibt dein Fortschritt erhalten; " +
        "jede gelernte Sprache hat ihre eigene Box.",
    resetButton = "Box zurücksetzen …",
    resetHint = "Löscht Fortschritt und Verlauf dieser Box — die Inhalte bleiben.",
    resetConfirm = "Alle Lernfortschritte für %s löschen und neu mit den ersten Wörtern beginnen?",
    cancel = "Abbrechen",
    reset = "Zurücksetzen",

    copyPrompt = "Einmal auf %s abschreiben …",
    copyMismatch = "Noch nicht ganz — das Wort steht oben.",
    skipStep = "Überspringen",

    caughtUpTitle = "Gerade ist nichts dran",
    dayReviews = "%d Wiederholungen",
    dayNewCards = "%d Frischlinge",
    dayConsolidated = "%d gefestigt",
    tomorrowPacked = "Deine gepackten Wörter sind in der nächsten Runde dabei.",
    tomorrowFresh = "Morgen gibt es frische Karten. Bis dann! 👋",
    tomorrowDue = "Morgen kannst du %d Karten wiederholen.",

    roundNew = "%d neu",
    roundConsolidated = "%d gefestigt",
    roundReviewed = "%d wiederholt",
    roundAllDone = "Alles erledigt",
    restHint = "Heute sitzt wenig — ein Kopf, der müde ist, behält nichts mehr. " +
        "Morgen geht's leichter.",
    streakRecord = "Dein längster Lauf!",

    progressTitle = "Fortschritt",
    last14Days = "Letzte 14 Tage",
    activityDays = "Aktivität der letzten 14 Tage: an %d Tagen gelernt",
    streakDays = "Serie: %d Tage",
    dayOne = "Tag",
    dayMany = "Tage",
)
