package net.spross.app

/**
 * The English chrome table.
 *
 * Also the one every source without chrome of its own falls back to ([Chrome.forSource]).
 *
 * GENERATED from App/Sources/Resources/Localizable.xcstrings by scripts/chrome.py —
 * do not edit. Change the wording in the String Catalog, run `scripts/chrome.py --fix`,
 * and both phones say the same sentence by construction.
 */
internal val ChromeEn = Chrome(
    heuteTitle = "Today",
    practice = "Practice",
    extraRound = "One more round?",
    doneToday = "Done for today",
    dueLabel = "due",
    newLabel = "new",
    consolidatedLabel = "consolidated",
    freshLabel = "fresh",
    chooseTitle = "Welcome to Spross!",
    chooseSubtitle = "First, your languages.",
    iSpeak = "I speak",
    iLearn = "I'm learning",
    letsGo = "Let's go!",
    back = "Back",
    whyTitle = "What Spross is for",
    whyBreadthTitle = "Sown, not crammed",
    whyBreadthBody = "A few new words a day, spaced so they stay. Better to know many words " +
        "a little than a few perfectly.",
    whyCompanionTitle = "A companion, not a replacement",
    whyCompanionBody = "Spross doesn't replace your course or your language partner. Your " +
        "vocabulary keeps growing between conversations, so you have more to say next time.",
    whyGrammarTitle = "Grammar comes from speaking",
    whyGrammarBody = "Spross doesn't teach grammar, just the gender a word carries. Where " +
        "you actually use the words, the rest takes care of itself.",
    firstRoundTitle = "Your first round",
    firstRoundRecognize = "When Spross shows you a word, take a moment. Does it ring a bell?",
    firstRoundGrade = "Then you reveal and say how well you knew it. Honest beats generous: " +
        "your answer decides when you see the word again.",
    firstRoundWrite = "A word you didn't know gets written once. When it turns up again, you " +
        "type it from memory.",
    check = "Check",
    reveal = "Reveal",
    next = "Next",
    also = "also: %s",
    typoNote = "Small typo – still counts!",
    otherWordNote = "By the way: %1\$s means “%2\$s”",
    answerPlaceholder = "In %s …",
    ratingQuestion = "How well did you know it?",
    coachRecognize = "Take a moment. Does it ring a bell?",
    coachGrade = "Answer honestly — it decides when you see it again.",
    coachWrite = "Write it once, so it sinks in.",
    hard = "Shaky",
    good = "Knew it",
    unknown = "Not at all",
    sessionDone = "All done!",
    keepPracticing = "Keep practicing",
    finish = "Done",
    pluralEquals = "= pl.",
    pluralOnly = "pl. only",
    pluralForm = "pl. %s",
    readAloud = "Read words aloud",
    stateOn = "on",
    stateOff = "off",
    pronounce = "Pronounce",
    aboutButton = "About",
    updateButton = "Updates",
    updateOfferTitle = "Newer versions",
    updateOfferBody = "Obtainium watches this app's releases and offers each new version as " +
        "it appears. Without it, every update is a download by hand.",
    updateViaObtainium = "Get Obtainium",
    updateDownload = "Download directly",
    audioToggle = "Read words aloud",
    audioToggleHint = "Read words aloud during review — switched on, it plays through a " +
        "silenced phone too. Tapping a word speaks it again, always.",
    creditsTitle = "Legal & licenses",
    creditsRecordings = "%d recordings",
    creditsUnmodified = "Recordings shipped unmodified",
    creditsCommons = "Recordings from Wikimedia Commons",
    trainingTitle = "Sprossen",
    trainingSubtitle = "Free practice — no schedule, no limit",
    lettersTitle = "Letters",
    lettersHear = "Which letter is this?",
    lettersSpell = "What's missing in the word?",
    lettersDictation = "Write what you hear",
    letterChoice = "Letter %s",
    replayPrompt = "Play it again",
    promptInLanguage = "in %s",
    level = "Sprosse %s",
    streak = "🔥 %s in a row",
    almostTypo = "Almost! Correct spelling",
    almostHeard = "You heard",
    audioOff = "Sound is off",
    enableSound = "Turn sound on",
    tasksDoneOne = "%d task 🎯",
    tasksDone = "%d tasks 🎯",
    bestStreak = "Best streak: 🔥 %s in a row",
    answerCorrect = "Correct",
    answerAlmost = "Almost correct",
    answerWrong = "Wrong",
    close = "Close",
    numbersTitle = "Numbers",
    numbersPage = "Numbers · %s",
    lettersPage = "Letters · %s",
    overviewPractice = "Practice",
    overviewStart = "Start",
    tapToHear = "Every row speaks when tapped",
    numbersReference = "How this language counts",
    numbersNotes = "What to watch out for",
    numberSections = mapOf(
        "base" to "Zero to fifteen",
        "tens" to "The tens",
        "irregulars" to "Sixteen to thirty",
        "compounds" to "Put together",
        "hundreds" to "The hundreds",
        "places" to "Thousand, million, billion",
        "forms" to "Beyond counting",
    ),
    variantClock = "Time",
    variantPhrases = "Sentences",
    variantForms = "Forms",
    modifierReverse = "Reversed",
    modifierReverseHint = "The reading is shown, the digits are owed.",
    modifierFast = "Fast",
    modifierFastHint = "One clean answer per Sprosse instead of two.",
    modifierMix = "Mixed up",
    modifierMixHint = "The direction flips every task, and forms grow to the size the " +
        "numbers reached.",
    combineLocked = "Several in one run, once everything is unlocked.",
    unlockPrefix = "Unlocks at:",
    digitsOne = "🔢 %d digit",
    digitsMany = "🔢 %d digits",
    record = "Record %s",
    streakSpoken = "Streak: %s in a row",
    recordSpoken = ", record %s",
    answerDigits = "In digits …",
    newPlace = "New place: %s",
    lookUp = "Look up numbers",
    newRecord = "New record!",
    stageChoiceEasy = "Four tiles",
    stageChoiceEasyHint = "Find the letter you heard among four",
    stageChoiceConfusable = "Lookalike tiles",
    stageChoiceConfusableHint = "The same choice, between letters that are easy to mix up",
    stageTyped = "Typing",
    stageTypedHint = "Write the letter yourself, with nothing to pick from",
    stageDictation = "Dictation",
    stageDictationHint = "Write whole words from your own box by ear",
    stageDictationLocked = "Needs more consolidated words this device can read out",
    stageEntry = "your run starts here",
    lettersUnavailable = "This device cannot say a letter yet — that needs a voice for the " +
        "language.",
    alphabetTitle = "Alphabet",
    alphabetSpeakName = "Hear the name",
    alphabetSpeakExample = "Hear the example",
    countriesTitle = "Countries",
    countriesPage = "Countries · %s",
    countriesReference = "The atlas",
    countriesPace = "Every run opens at Sprosse 1 and climbs on by itself.",
    countriesBest = "Furthest so far: Sprosse %s",
    countriesFastHint = "One clean answer per Sprosse instead of three.",
    countriesReverseHint = "The question comes in %s, the answer is owed in %s.",
    countryRungs = listOf(
        "The countries of your languages",
        "The names of the languages",
        "The people",
        "The app's languages",
        "What is spoken there?",
        "Common languages of the world",
        "The flag alone",
        "Less common countries and languages",
        "From language to country",
    ),
    countryRungHints = listOf(
        "What is a country one of your languages is at home in called?",
        "Plus: what is the language itself called?",
        "Plus: what are the people from there called?",
        "The circle widens — the same questions, more countries.",
        "Plus: which language is spoken in this country?",
        "More countries again, the same questions.",
        "Plus: which country is this, from its flag alone? Not in a reversed run.",
        "The rest of what the atlas knows.",
        "Plus: where is this language spoken?",
    ),
    countryTiers = listOf(
        "Your languages",
        "The app's languages",
        "Common languages",
        "Less common languages",
    ),
    countryAskCountry = "What is this country called?",
    countryAskFlag = "Which country is this?",
    countryAskLanguage = "What is this language called?",
    countryAskNationality = "What are these people called?",
    countryAskSpokenIn = "Which language is spoken there?",
    countryAskSpokenWhere = "Where is this language spoken?",
    boxTitle = "The box",
    boxNav = "Box",
    boxSubtitle = "%1\$s of %2\$s cards in progress",
    ownWordsTitle = "Your own words",
    ownWordsExplainer = "Your own words stand in an area of their own. A growing catalog " +
        "never touches them.",
    packArea = "Add to box (%s)",
    packDone = "All packed",
    packWord = "Pack this word",
    packedWord = "Packed",
    suspended = "Paused",
    wake = "Wake",
    progressFresh = "%s fresh",
    phrasesLocked = "%d sentences",
    phrasesLockedSpoken = "%d sentences locked",
    stateExpanded = "expanded",
    stateCollapsed = "collapsed",
    phaseLearning = "Learning",
    phaseReview = "Solid",
    phaseRelearning = "Shaky",
    search = "Search",
    searchPlaceholder = "Word or area",
    searchHint = "Words in either language, and the names of the areas.",
    searchAreas = "Areas",
    searchWords = "Words",
    searchNothing = "Nothing for “%s” in the box.",
    searchWriteOwn = "Write “%s” yourself",
    searchClear = "Clear search",
    ownWordTitle = "Your own word",
    ownWordInLanguage = "In %s",
    ownWordPicture = "Picture (optional)",
    ownWordAdd = "Add",
    ownWordRemove = "Delete word",
    settingsTitle = "Settings",
    profileHint = "Switching the language you speak keeps all your progress; each language " +
        "you learn has its own box.",
    resetButton = "Reset %s …",
    resetHint = "Deletes progress and history — your own words and your other languages stay.",
    resetConfirm = "Delete all learning progress for %s and start over with the first words?",
    cancel = "Cancel",
    reset = "Reset",
    copyPrompt = "Write it once in %s …",
    copyMismatch = "Not quite — the word is right above.",
    skipStep = "Skip",
    caughtUpTitle = "Nothing's due right now",
    dayReviews = "%d reviews",
    dayReviewsOne = "%d review",
    dayNewCards = "%d newbies",
    dayNewCardsOne = "%d newbie",
    dayConsolidated = "%s solidified",
    dayAhead = "%d refreshers",
    dayAheadOne = "%d refresher",
    tomorrowPacked = "Your packed words are in the next round.",
    tomorrowFresh = "Fresh cards tomorrow. See you then! 👋",
    tomorrowDue = "Tomorrow you can review %d cards.",
    headlineReviews = listOf(
        "Your round is ready",
        "A stack is ready",
        "The box has something for you",
    ),
    headlineWarmUp = listOf(
        "Time for a refresher",
        "A reunion with familiar words",
        "A quick pass through the familiar",
    ),
    headlineFreshSet = listOf(
        "Up for some new words?",
        "Newbies on the table",
        "A few newbies to get to know",
    ),
    sessionSomeCards = "A few cards for you.",
    sessionHeldBack = "%d more cards are still waiting for you.",
    sessionStart = "Let's go!",
    emptyBoxTitle = "Your box is still empty",
    emptyBoxMessage = "Add an area directly, or set how many cards you learn at a time.",
    emptyBoxAction = "Go to box",
    errorTitle = "Oops",
    errorCatalogMissing = "The content could not be loaded. (catalog missing from the app " +
        "bundle)",
    errorContentUnavailable = "The content could not be loaded. (%s)",
    errorUnknownProfile = "Unknown language profile (%1\$s → %2\$s).",
    errorResetFailed = "Reset failed. (%s)",
    roundNew = "%s new",
    roundConsolidated = "%s consolidated",
    roundReviewed = "%s reviewed",
    roundAllDone = "All done",
    restHint = "Not much is sticking today — a tired head keeps nothing. Tomorrow will go " +
        "easier.",
    streakRecord = "Your longest run yet!",
    growthGrew = "Some of it sticks today too",
    growthOpened = "Your first words in good soil",
    growthBlooming = listOf(
        "Saying what you sowed",
        "You've brought this into bloom",
        "Your tending shows",
    ),
    growthSown = listOf(
        "You've sown here",
        "You've got this sprouting",
        "You're planting, word by word",
    ),
    growthGrown = listOf(
        "You've grown what you can say",
        "Your words root deeper now",
        "Words are settling in",
    ),
    last14Days = "Last 14 days",
    activityDays = "Activity over the last 14 days: practiced on %d days",
    streakDays = "Streak: %d days",
    streakDaysOne = "Streak: %d day",
    dayOne = "day",
    dayMany = "days",
)
