package net.spross.app

/**
 * The German chrome table. Wording follows the iOS String Catalog
 * (`App/Sources/Resources/Localizable.xcstrings`) key for key, so a learner meeting the
 * same surface on either platform reads the same sentence.
 */
internal val ChromeDe = Chrome(
    heuteTitle = "Heute",
    practice = "Üben",
    extraRound = "Extra-Runde",
    doneToday = "Für heute geschafft!",
    emptyState = "Die Box wächst, während dein Material sitzt.",
    dueLabel = "fällig",
    newLabel = "neu",
    consolidatedLabel = "gefestigt",
    freshLabel = "frisch",
    changeLanguages = "Sprachen ändern",
    chooseTitle = "Was möchtest du lernen?",
    iSpeak = "Ich spreche",
    iLearn = "Ich lerne",
    conceptsSuffix = "Begriffe",
    letsGo = "Los geht's",
    backLabel = "Zurück",
    check = "Prüfen",
    reveal = "Aufdecken",
    next = "Weiter",
    alsoPrefix = "auch:",
    typoNote = "Kleiner Tippfehler – zählt!",
    otherWordNote = "Übrigens: %1\$s heißt „%2\$s“",
    answerPlaceholder = "In %s …",
    again = "Nochmal",
    hard = "Schwer",
    good = "Gut",
    easy = "Leicht",
    unknown = "Unbekannt",
    sessionDone = "Geschafft!",
    summaryLine = "%d neu · %d gefestigt · %d wiederholt",
    keepPracticing = "Weiter üben",
    finish = "Fertig",
    pluralEquals = "= Pl.",
    pluralOnly = "nur Pl.",
    pluralPrefix = "Pl. ",
    readAloud = "Aussprache vorlesen",
    stateOn = "an",
    stateOff = "aus",
    pronounce = "Aussprechen",
    aboutButton = "Info",
    audioToggle = "Wörter vorlesen",
    audioToggleHint = "Wörter beim Üben automatisch vorlesen. Tippen auf ein Wort " +
        "spricht es erneut — auch bei ausgeschaltetem Vorlesen.",
    creditsTitle = "Sprecher & Lizenzen",
    creditsRecordings = "%d Aufnahmen",
    creditsUnmodified = "Aufnahmen unverändert übernommen",
    creditsCommons = "Aufnahmen von Wikimedia Commons",
    trainingTitle = "Werkstatt",
    trainingSubtitle = "Freies Üben – ohne Termin, ohne Limit",
    lettersTitle = "Buchstaben",
    lettersHear = "Welcher Buchstabe ist das?",
    lettersSpell = "Was fehlt im Wort?",
    lettersDictation = "Schreib, was du hörst",
    letterChoice = "Buchstabe %s",
    replayPrompt = "Noch einmal anhören",
    promptInLanguage = "auf %s",
    level = "Stufe %d",
    streak = "🔥 %d in Folge",
    typoCorrection = "Fast! Richtig geschrieben: %s",
    heardInstead = "Gehört war: %s",
    audioOff = "Ton ist aus",
    enableSound = "Ton einschalten",
    tasksDoneOne = "1 Aufgabe 🎯",
    tasksDone = "%d Aufgaben 🎯",
    bestStreak = "Beste Serie: 🔥 %d in Folge",
    answerCorrect = "Richtig",
    answerWrong = "Falsch",

    close = "Schließen",
    numbersTitle = "Zahlen",
    numbersPage = "Zahlen · %s",
    lettersPage = "Buchstaben · %s",
    overviewPractice = "Üben",
    overviewStart = "Los",
    numbersReference = "Wie diese Sprache zählt",
    numbersNotes = "Darauf kommt es an",
    numberSections = mapOf(
        "ones" to "Null bis neun",
        "teens" to "Zehn bis neunzehn",
        "tens" to "Die Zehner",
        "twenties" to "Die Zwanziger",
        "compounds" to "Zusammengesetzt",
        "hundreds" to "Die Hunderter",
        "places" to "Tausend, Million, Milliarde",
        "forms" to "Andere Schreibweisen",
    ),
    variantClock = "Uhrzeit",
    variantPhrases = "Sätze",
    variantForms = "Zahlformen",
    modifierReverse = "Umgekehrt",
    modifierReverseHint = "Das Zahlwort steht da, die Ziffern sind gefragt.",
    modifierFast = "Schnell",
    modifierFastHint = "Eine saubere Antwort pro Stufe statt zwei.",
    modifierMix = "Bunt gemischt",
    modifierMixHint = "Die Richtung wechselt bei jeder Aufgabe, " +
        "und Formen werden so groß wie die Zahlen.",
    combineLocked = "Mehreres in einem Lauf, sobald alles freigeschaltet ist.",
    unlockPrefix = "Freischalten:",

    digitsOne = "🔢 1 Stelle",
    digitsMany = "🔢 %d Stellen",
    record = "Rekord %d",
    streakSpoken = "Serie: %d in Folge",
    recordSpoken = ", Rekord %d",
    answerDigits = "In Ziffern …",
    newPlace = "Neue Stelle: %s",
    lookUp = "Zahlen nachschlagen",
    newRecord = "Neuer Rekord!",

    stageChoiceEasy = "Vier Kacheln",
    stageChoiceEasyHint = "Den gehörten Buchstaben unter vieren finden",
    stageChoiceConfusable = "Ähnliche Kacheln",
    stageChoiceConfusableHint = "Dieselbe Wahl, aber mit Buchstaben, " +
        "die leicht zu verwechseln sind",
    stageTyped = "Tippen",
    stageTypedHint = "Den Buchstaben selbst schreiben, ohne Auswahl",
    stageDictation = "Diktat",
    stageDictationHint = "Ganze Wörter aus dem eigenen Kasten nach Gehör schreiben",
    stageDictationLocked = "Braucht mehr gefestigte Wörter, die dieses Gerät vorlesen kann",
    stageEntry = "hier geht es los",
    lettersUnavailable = "Dieses Gerät kann noch keinen Buchstaben vorsprechen — " +
        "dafür braucht es eine Stimme für die Sprache.",
    alphabetTitle = "Alphabet",
    alphabetSpeakName = "Name anhören",
    alphabetSpeakExample = "Beispiel anhören",

    boxTitle = "Die Box",
    boxNav = "Box",
    boxSubtitle = "%1\$d von %2\$d Karten in Arbeit",
    ownWordsTitle = "Eigene Wörter",
    ownWordsExplainer = "Eigene Wörter stehen in ihrem eigenen Bereich. " +
        "Ein wachsender Katalog rührt sie nicht an.",
    packArea = "Pack in die Box (%d)",
    packDone = "Alles eingepackt",
    packWord = "Dieses Wort einpacken",
    packedWord = "Eingepackt",
    suspended = "Pausiert",
    wake = "Wecken",
    progressFresh = "%d frisch",
    phrasesLocked = "%d Sätze",
    phrasesLockedSpoken = "%d Sätze gesperrt",
    stateExpanded = "ausgeklappt",
    stateCollapsed = "eingeklappt",
    phaseLearning = "Lernt",
    phaseReview = "Sitzt",
    phaseRelearning = "Wackelt",

    search = "Suchen",
    searchPlaceholder = "Wort oder Bereich",
    searchHint = "Wörter beider Sprachen und die Namen der Bereiche.",
    searchAreas = "Bereiche",
    searchWords = "Wörter",
    searchNothing = "Nichts zu „%s“ in der Box.",
    searchWriteOwn = "„%s“ selbst eintragen",
    searchClear = "Suche löschen",

    ownWordTitle = "Eigenes Wort",
    ownWordInLanguage = "Auf %s",
    ownWordPicture = "Bild (optional)",
    ownWordAdd = "Anlegen",
    ownWordRemove = "Wort löschen",

    settingsTitle = "Einstellungen",
    profileHint = "Beim Wechsel der Ausgangssprache bleibt dein Fortschritt erhalten; " +
        "jede gelernte Sprache hat ihre eigene Box.",
    resetButton = "Box zurücksetzen …",
    resetHint = "Löscht Fortschritt und Verlauf dieser Box — die Inhalte bleiben.",
    resetConfirm = "Alle Lernfortschritte für %s löschen und neu mit den ersten Wörtern beginnen?",
    cancel = "Abbrechen",
    reset = "Zurücksetzen",

    copyPrompt = "Einmal auf %s abschreiben …",
    copyMismatch = "Noch nicht ganz — das Wort steht oben.",
    skipStep = "Überspringen",

    caughtUpTitle = "Gerade ist nichts dran",
    dayReviews = "%d Wiederholungen",
    dayReviewsOne = "1 Wiederholung",
    dayNewCards = "%d Frischlinge",
    dayNewCardsOne = "1 Frischling",
    dayConsolidated = "%d gefestigt",
    dayAhead = "%d Auffrischer",
    dayAheadOne = "1 Auffrischer",
    tomorrowPacked = "Deine gepackten Wörter sind in der nächsten Runde dabei.",
    tomorrowFresh = "Morgen gibt es frische Karten. Bis dann! 👋",
    tomorrowDue = "Morgen kannst du %d Karten wiederholen.",

    headlineReviews = listOf(
        "Deine Runde ist startklar",
        "Ein Stapel liegt bereit",
        "Die Box hat was für dich",
    ),
    headlineWarmUp = listOf(
        "Zeit zum Auffrischen",
        "Ein Wiedersehen mit Bekanntem",
        "Kurz durchs Bekannte",
    ),
    headlineFreshSet = listOf(
        "Lust auf neue Wörter?",
        "Frischlinge liegen bereit",
        "Ein paar Frischlinge zum Kennenlernen",
    ),
    sessionSomeCards = "Ein paar Karten für dich.",
    sessionHeldBack = "%d weitere Karten warten noch auf dich.",
    sessionStart = "Los geht's!",

    emptyBoxTitle = "Deine Box ist noch leer",
    emptyBoxMessage = "Pack einen Bereich direkt hinein — die Box wächst, während dein Material sitzt.",
    emptyBoxAction = "Zur Box",

    errorTitle = "Ups",
    errorCatalogMissing = "Die Inhalte konnten nicht geladen werden. (catalog fehlt in der App)",
    errorContentUnavailable = "Die Inhalte konnten nicht geladen werden. (%s)",
    errorUnknownProfile = "Unbekanntes Sprachprofil (%1\$s → %2\$s).",
    errorResetFailed = "Zurücksetzen fehlgeschlagen. (%s)",

    roundNew = "%d neu",
    roundConsolidated = "%d gefestigt",
    roundReviewed = "%d wiederholt",
    roundAllDone = "Alles erledigt",
    restHint = "Heute sitzt wenig — ein Kopf, der müde ist, behält nichts mehr. " +
        "Morgen geht's leichter.",
    streakRecord = "Dein längster Lauf!",

    growthGrew = "Auch heute bleibt was hängen",
    growthOpened = "Deine ersten Wörter in guter Erde",
    growthBlooming = listOf(
        "Jetzt sagst du, was du gesät hast",
        "Hier blüht, was du kannst",
        "Du hast es gepflegt, jetzt trägt's",
    ),
    growthSown = listOf(
        "Du hast hier gesät",
        "Das keimt nun in dir",
        "Frisch von dir gesetzt",
    ),
    growthGrown = listOf(
        "Hier wächst dir was zu sagen",
        "Du hast tiefe Wurzeln geschlagen",
        "Mittlerweile sitzt's bei dir",
    ),

    progressTitle = "Fortschritt",
    last14Days = "Letzte 14 Tage",
    activityDays = "Aktivität der letzten 14 Tage: an %d Tagen gelernt",
    streakDays = "Serie: %d Tage",
    streakDaysOne = "Serie: 1 Tag",
    dayOne = "Tag",
    dayMany = "Tage",
)
