package net.spross.app

/**
 * The English chrome table, and the one every source without chrome of its own falls
 * back to ([Chrome.forSource]). Wording follows the iOS String Catalog key for key.
 */
internal val ChromeEn = Chrome(
    heuteTitle = "Today",
    practice = "Practice",
    extraRound = "Extra round",
    doneToday = "Done for today!",
    emptyState = "The box grows while your material sits.",
    dueLabel = "due",
    newLabel = "new",
    consolidatedLabel = "consolidated",
    freshLabel = "fresh",
    changeLanguages = "Change languages",
    chooseTitle = "What do you want to learn?",
    iSpeak = "I speak",
    iLearn = "I learn",
    conceptsSuffix = "terms",
    letsGo = "Let's go",
    backLabel = "Back",
    check = "Check",
    reveal = "Reveal",
    next = "Next",
    alsoPrefix = "also:",
    typoNote = "Small typo – still counts!",
    otherWordNote = "By the way: %1\$s means “%2\$s”",
    answerPlaceholder = "In %s …",
    again = "Again",
    hard = "Hard",
    good = "Good",
    easy = "Easy",
    sessionDone = "Done!",
    summaryLine = "%d new · %d strengthened · %d reviewed",
    keepPracticing = "Keep practicing",
    finish = "Finish",
    pluralEquals = "= pl.",
    pluralOnly = "pl. only",
    pluralPrefix = "pl. ",
    readAloud = "Read words aloud",
    stateOn = "on",
    stateOff = "off",
    pronounce = "Pronounce",
    aboutButton = "About",
    audioToggle = "Read words aloud",
    audioToggleHint = "Read words aloud during review. Tapping a word speaks it " +
        "again — even when read-aloud is off.",
    creditsTitle = "Voices & licences",
    creditsRecordings = "%d recordings",
    creditsUnmodified = "Recordings shipped unmodified",
    creditsCommons = "Recordings from Wikimedia Commons",
    trainingTitle = "Training",
    lettersTitle = "Letters",
    lettersHear = "Which letter is this?",
    lettersSpell = "What's missing in the word?",
    lettersDictation = "Write what you hear",
    letterChoice = "Letter %s",
    replayPrompt = "Play it again",
    promptInLanguage = "in %s",
    level = "Level %d",
    streak = "🔥 %d in a row",
    typoCorrection = "Almost! Correct spelling: %s",
    heardInstead = "You heard: %s",
    audioOff = "Sound is off",
    enableSound = "Turn sound on",
    tasksDone = "%d tasks 🎯",
    bestStreak = "Best streak: 🔥 %d in a row",
    answerCorrect = "Correct",
    answerWrong = "Wrong",
    correctAnswer = "Correct: %s",

    boxTitle = "The box",
    boxNav = "Box",
    boxSubtitle = "%1\$d of %2\$d cards in progress",
    ownWordsTitle = "Your own words",
    ownWordsExplainer = "Your own words stand in an area of their own. " +
        "A growing catalog never touches them.",
    packArea = "Add to box (%d)",
    packDone = "All packed",
    packWord = "Pack this word",
    packedWord = "Packed",
    suspended = "Paused",
    wake = "Wake",
    phrasesLocked = "%d sentences",
    phaseLearning = "Learning",
    phaseReview = "Solid",
    phaseRelearning = "Shaky",

    search = "Search",
    searchPlaceholder = "Word or area",
    searchHint = "Words in either language, and the names of the areas.",
    searchAreas = "Areas",
    searchWords = "Words",
    searchNothing = "Nothing for “%s” in the box.",
    searchWriteOwn = "Write “%s” yourself",
    searchClear = "Clear search",

    ownWordTitle = "Your own word",
    ownWordInLanguage = "In %s",
    ownWordPicture = "Picture (optional)",
    ownWordAdd = "Add",
    ownWordRemove = "Delete word",

    settingsTitle = "Settings",
    profileHint = "Switching the language you speak keeps all your progress; " +
        "each language you learn has its own box.",
    resetButton = "Reset box …",
    resetHint = "Deletes this box's progress and history — the content stays.",
    resetConfirm = "Delete all learning progress for %s and start over with the first words?",
    cancel = "Cancel",
    reset = "Reset",

    copyPrompt = "Write it once in %s …",
    copyMismatch = "Not quite — the word is right above.",
    skipStep = "Skip",

    caughtUpTitle = "Nothing's due right now",
    dayReviews = "%d reviews",
    dayNewCards = "%d newbies",
    dayConsolidated = "%d solidified",
    tomorrowPacked = "Your packed words are in the next round.",
    tomorrowFresh = "Fresh cards tomorrow. See you then! 👋",
    tomorrowDue = "Tomorrow you can review %d cards.",

    roundNew = "%d new",
    roundConsolidated = "%d consolidated",
    roundReviewed = "%d reviewed",
    roundAllDone = "All done",
    restHint = "Not much is sticking today — a tired head keeps nothing. " +
        "Tomorrow will go easier.",
    streakRecord = "Your longest run yet!",

    progressTitle = "Progress",
    last14Days = "Last 14 days",
    activityDays = "Activity over the last 14 days: practiced on %d days",
    streakDays = "Streak: %d days",
    dayOne = "day",
    dayMany = "days",
)
