package net.spross.app

/**
 * The German chrome table.
 *
 * GENERATED from App/Sources/Resources/Localizable.xcstrings by scripts/chrome.py —
 * do not edit. Change the wording in the String Catalog, run `scripts/chrome.py --fix`,
 * and both phones say the same sentence by construction.
 */
internal val ChromeDe = Chrome(
    heuteTitle = "Heute",
    practice = "Üben",
    extraRound = "Noch eine Runde?",
    doneToday = "Für heute geschafft",
    dueLabel = "fällig",
    newLabel = "neu",
    consolidatedLabel = "gefestigt",
    freshLabel = "frisch",
    chooseTitle = "Willkommen bei Spross!",
    chooseSubtitle = "Zuerst deine Sprachen.",
    iSpeak = "Ich spreche",
    iLearn = "Ich lerne",
    letsGo = "Los geht's!",
    back = "Zurück",
    whyTitle = "Wofür Spross da ist",
    whyBreadthTitle = "Gesät, nicht gepaukt",
    whyBreadthBody = "Ein paar neue Wörter am Tag, so verteilt, dass sie bleiben. Lieber " +
        "viele Wörter ein bisschen kennen als wenige perfekt.",
    whyCompanionTitle = "Begleiter, kein Ersatz",
    whyCompanionBody = "Spross ersetzt weder deinen Kurs noch deinen Sprachpartner. Zwischen " +
        "den Gesprächen wächst dein Wortschatz weiter, damit du beim nächsten Mal mehr zu " +
        "sagen hast.",
    whyGrammarTitle = "Grammatik kommt vom Sprechen",
    whyGrammarBody = "Spross bringt dir keine Grammatik bei, nur das Geschlecht der Wörter. " +
        "Wo du die Wörter wirklich benutzt, kommt der Rest von selbst.",
    firstRoundTitle = "Deine erste Runde",
    firstRoundRecognize = "Wenn Spross dir ein Wort zeigt, nimm dir einen Moment: Kommt es " +
        "dir bekannt vor?",
    firstRoundGrade = "Dann deckst du auf und sagst, wie gut du es wusstest. Ehrlich schlägt " +
        "großzügig: Deine Antwort entscheidet, wann du das Wort wiedersiehst.",
    firstRoundWrite = "Ein Wort, das du nicht wusstest, schreibst du einmal ab. Taucht es " +
        "wieder auf, tippst du es aus dem Gedächtnis.",
    check = "Prüfen",
    reveal = "Aufdecken",
    next = "Weiter",
    also = "auch: %s",
    typoNote = "Kleiner Tippfehler – zählt!",
    otherWordNote = "Übrigens: %1\$s heißt „%2\$s“",
    answerPlaceholder = "Auf %s …",
    ratingQuestion = "Wie gut wusstest du es?",
    coachRecognize = "Nimm dir einen Moment: Kommt es dir bekannt vor?",
    coachGrade = "Ehrlich antworten — das entscheidet, wann du es wiedersiehst.",
    coachWrite = "Einmal abschreiben, damit es sitzt.",
    hard = "Wackelig",
    good = "Wusste ich",
    unknown = "Gar nicht",
    sessionDone = "Geschafft!",
    keepPracticing = "Weiter üben",
    finish = "Fertig",
    pluralEquals = "= Pl.",
    pluralOnly = "nur Pl.",
    pluralForm = "Pl. %s",
    readAloud = "Aussprache vorlesen",
    stateOn = "an",
    stateOff = "aus",
    pronounce = "Aussprechen",
    aboutButton = "Info",
    updateButton = "Updates",
    updateOfferTitle = "Neuere Versionen",
    updateOfferBody = "Obtainium verfolgt die Veröffentlichungen dieser App und bietet jede " +
        "neue Version an, sobald es sie gibt. Ohne Obtainium ist jedes Update ein Download " +
        "von Hand.",
    updateViaObtainium = "Obtainium holen",
    updateDownload = "Direkt herunterladen",
    audioToggle = "Wörter vorlesen",
    audioToggleHint = "Wörter beim Üben automatisch vorlesen — eingeschaltet auch bei " +
        "stummem Handy. Tippen auf ein Wort spricht es erneut, immer.",
    creditsTitle = "Impressum & Lizenzen",
    creditsRecordings = "%d Aufnahmen",
    creditsUnmodified = "Aufnahmen unverändert übernommen",
    creditsCommons = "Aufnahmen von Wikimedia Commons",
    trainingTitle = "Sprossen",
    trainingSubtitle = "Freies Üben – ohne Termin, ohne Limit",
    lettersTitle = "Buchstaben",
    lettersHear = "Welcher Buchstabe ist das?",
    lettersSpell = "Was fehlt im Wort?",
    lettersDictation = "Schreib, was du hörst",
    letterChoice = "Buchstabe %s",
    replayPrompt = "Noch einmal anhören",
    promptInLanguage = "auf %s",
    level = "Sprosse %s",
    streak = "🔥 %s in Folge",
    almostTypo = "Fast! Korrekte Schreibweise",
    almostHeard = "Gehört war",
    audioOff = "Ton ist aus",
    enableSound = "Ton einschalten",
    tasksDoneOne = "%d Aufgabe 🎯",
    tasksDone = "%d Aufgaben 🎯",
    bestStreak = "Beste Serie: 🔥 %s in Folge",
    answerCorrect = "Richtig",
    answerAlmost = "Fast richtig",
    answerWrong = "Falsch",
    close = "Schließen",
    numbersTitle = "Zahlen",
    numbersPage = "Zahlen · %s",
    lettersPage = "Buchstaben · %s",
    overviewPractice = "Üben",
    overviewStart = "Los",
    tapToHear = "Jede Zeile spricht beim Antippen",
    numbersReference = "Wie diese Sprache zählt",
    numbersNotes = "Darauf kommt es an",
    numberSections = mapOf(
        "base" to "Null bis fünfzehn",
        "tens" to "Die Zehner",
        "irregulars" to "Sechzehn bis dreißig",
        "compounds" to "Zusammengesetzt",
        "hundreds" to "Die Hunderter",
        "places" to "Tausend, Million, Milliarde",
        "forms" to "Mehr als Zählen",
    ),
    variantClock = "Uhrzeit",
    variantPhrases = "Sätze",
    variantForms = "Zahlformen",
    modifierReverse = "Umgekehrt",
    modifierReverseHint = "Das Zahlwort steht da, die Ziffern sind gefragt.",
    modifierFast = "Schnell",
    modifierFastHint = "Eine saubere Antwort pro Sprosse statt zwei.",
    modifierMix = "Bunt gemischt",
    modifierMixHint = "Die Richtung wechselt bei jeder Aufgabe, und Formen werden so groß " +
        "wie die Zahlen.",
    combineLocked = "Mehreres in einem Lauf, sobald alles freigeschaltet ist.",
    unlockPrefix = "Freischalten:",
    digitsOne = "🔢 %d Stelle",
    digitsMany = "🔢 %d Stellen",
    record = "Rekord %s",
    streakSpoken = "Serie: %s in Folge",
    recordSpoken = ", Rekord %s",
    answerDigits = "In Ziffern …",
    newPlace = "Neue Stelle: %s",
    lookUp = "Zahlen nachschlagen",
    newRecord = "Neuer Rekord!",
    stageChoiceEasy = "Vier Kacheln",
    stageChoiceEasyHint = "Den gehörten Buchstaben unter vieren finden",
    stageChoiceConfusable = "Ähnliche Kacheln",
    stageChoiceConfusableHint = "Dieselbe Wahl, aber mit Buchstaben, die leicht zu " +
        "verwechseln sind",
    stageTyped = "Tippen",
    stageTypedHint = "Den Buchstaben selbst schreiben, ohne Auswahl",
    stageDictation = "Diktat",
    stageDictationHint = "Ganze Wörter aus dem eigenen Kasten nach Gehör schreiben",
    stageDictationLocked = "Braucht mehr gefestigte Wörter, die dieses Gerät vorlesen kann",
    stageEntry = "hier geht es los",
    lettersUnavailable = "Dieses Gerät kann noch keinen Buchstaben vorsprechen — dafür " +
        "braucht es eine Stimme für die Sprache.",
    alphabetTitle = "Alphabet",
    alphabetSpeakName = "Name anhören",
    alphabetSpeakExample = "Beispiel anhören",
    countriesTitle = "Länder",
    countriesPage = "Länder · %s",
    countriesReference = "Der Atlas",
    countriesPace = "Jeder Durchgang beginnt bei Sprosse 1 und klettert von selbst weiter.",
    countriesBest = "Am weitesten gekommen: Sprosse %s",
    countriesFastHint = "Eine saubere Antwort pro Sprosse statt drei.",
    countriesReverseHint = "Gefragt wird auf %s, geantwortet auf %s.",
    countryRungs = listOf(
        "Die Länder eurer Sprachen",
        "Die Namen der Sprachen",
        "Die Leute",
        "Die Sprachen der App",
        "Wo spricht man was?",
        "Häufige Sprachen der Welt",
        "Nur die Flagge",
        "Seltenere Länder und Sprachen",
        "Von der Sprache zum Land",
    ),
    countryRungHints = listOf(
        "Wie heißt das Land, in dem eine eurer Sprachen zu Hause ist?",
        "Dazu: wie heißt die Sprache selbst?",
        "Dazu: wie heißen die Menschen von dort?",
        "Der Kreis wird größer – dieselben Fragen, mehr Länder.",
        "Dazu: welche Sprache spricht man in diesem Land?",
        "Noch mehr Länder, dieselben Fragen.",
        "Dazu: welches Land ist das, nur an der Flagge? Umgekehrt entfällt das.",
        "Was der Atlas sonst noch kennt.",
        "Dazu: wo spricht man diese Sprache?",
    ),
    countryTiers = listOf(
        "Eure Sprachen",
        "Die Sprachen der App",
        "Häufige Sprachen",
        "Seltenere Sprachen",
    ),
    countryAskCountry = "Wie heißt dieses Land?",
    countryAskFlag = "Welches Land ist das?",
    countryAskLanguage = "Wie heißt diese Sprache?",
    countryAskNationality = "Wie heißen diese Leute?",
    countryAskSpokenIn = "Welche Sprache spricht man dort?",
    countryAskSpokenWhere = "Wo spricht man diese Sprache?",
    boxTitle = "Die Box",
    boxNav = "Box",
    boxSubtitle = "%s von %s Karten in Arbeit",
    ownWordsTitle = "Eigene Wörter",
    ownWordsExplainer = "Eigene Wörter stehen in ihrem eigenen Bereich. Ein wachsender " +
        "Katalog rührt sie nicht an.",
    packArea = "Pack in die Box (%s)",
    packDone = "Alles eingepackt",
    packWord = "Dieses Wort einpacken",
    packedWord = "Eingepackt",
    suspended = "Pausiert",
    wake = "Wecken",
    progressFresh = "%s frisch",
    phrasesLocked = "%d Sätze",
    phrasesLockedSpoken = "%d Sätze gesperrt",
    stateExpanded = "ausgeklappt",
    stateCollapsed = "eingeklappt",
    phaseLearning = "Lernt",
    phaseReview = "Sitzt",
    phaseRelearning = "Wackelt",
    search = "Suchen",
    searchPlaceholder = "Wort oder Bereich",
    searchHint = "Wörter beider Sprachen und die Namen der Bereiche.",
    searchAreas = "Bereiche",
    searchWords = "Wörter",
    searchNothing = "Nichts zu „%s“ in der Box.",
    searchWriteOwn = "„%s“ selbst eintragen",
    searchClear = "Suche löschen",
    ownWordTitle = "Eigenes Wort",
    ownWordInLanguage = "Auf %s",
    ownWordPicture = "Bild (optional)",
    ownWordAdd = "Anlegen",
    ownWordRemove = "Wort löschen",
    settingsTitle = "Einstellungen",
    profileHint = "Beim Wechsel der Ausgangssprache bleibt dein Fortschritt erhalten; jede " +
        "gelernte Sprache hat ihre eigene Box.",
    resetButton = "%s zurücksetzen …",
    resetHint = "Löscht Fortschritt und Verlauf — deine eigenen Wörter und deine anderen " +
        "Sprachen bleiben.",
    resetConfirm = "Alle Lernfortschritte für %s löschen und neu mit den ersten Wörtern " +
        "beginnen?",
    cancel = "Abbrechen",
    reset = "Zurücksetzen",
    copyPrompt = "Einmal auf %s abschreiben …",
    copyMismatch = "Noch nicht ganz — das Wort steht oben.",
    skipStep = "Überspringen",
    caughtUpTitle = "Gerade ist nichts dran",
    dayReviews = "%d Wiederholungen",
    dayReviewsOne = "%d Wiederholung",
    dayNewCards = "%d Frischlinge",
    dayNewCardsOne = "%d Frischling",
    dayConsolidated = "%s gefestigt",
    dayAhead = "%d Auffrischer",
    dayAheadOne = "%d Auffrischer",
    tomorrowPacked = "Deine gepackten Wörter sind in der nächsten Runde dabei.",
    tomorrowFresh = "Morgen gibt es frische Karten. Bis dann! 👋",
    tomorrowDue = "Morgen kannst du %d Karten wiederholen.",
    headlineReviews = listOf(
        "Deine Runde ist startklar",
        "Ein Stapel liegt bereit",
        "Die Box hat was für dich",
    ),
    headlineWarmUp = listOf(
        "Zeit zum Auffrischen",
        "Ein Wiedersehen mit Bekanntem",
        "Kurz durchs Bekannte",
    ),
    headlineFreshSet = listOf(
        "Lust auf neue Wörter?",
        "Frischlinge liegen bereit",
        "Ein paar Frischlinge zum Kennenlernen",
    ),
    sessionSomeCards = "Ein paar Karten für dich.",
    sessionHeldBack = "%d weitere Karten warten noch auf dich.",
    sessionStart = "Los geht's!",
    emptyBoxTitle = "Deine Box ist noch leer",
    emptyBoxMessage = "Pack einen Bereich direkt hinein oder stell ein, wie viele Karten du " +
        "gleichzeitig lernst.",
    emptyBoxAction = "Zur Box",
    errorTitle = "Ups",
    errorCatalogMissing = "Die Inhalte konnten nicht geladen werden. (catalog fehlt im " +
        "App-Bundle)",
    errorContentUnavailable = "Die Inhalte konnten nicht geladen werden. (%s)",
    errorUnknownProfile = "Unbekanntes Sprachprofil (%s → %s).",
    errorResetFailed = "Zurücksetzen fehlgeschlagen. (%s)",
    roundNew = "%s neu",
    roundConsolidated = "%s gefestigt",
    roundReviewed = "%s wiederholt",
    roundAllDone = "Alles erledigt",
    restHint = "Heute sitzt wenig — ein Kopf, der müde ist, behält nichts mehr. Morgen " +
        "geht's leichter.",
    streakRecord = "Dein längster Lauf!",
    growthGrew = "Auch heute bleibt was hängen",
    growthOpened = "Deine ersten Wörter in guter Erde",
    growthBlooming = listOf(
        "Jetzt sagst du, was du gesät hast",
        "Hier blüht, was du kannst",
        "Du hast es gepflegt, jetzt trägt's",
    ),
    growthSown = listOf(
        "Du hast hier gesät",
        "Das keimt nun in dir",
        "Frisch von dir gesetzt",
    ),
    growthGrown = listOf(
        "Hier wächst dir was zu sagen",
        "Du hast tiefe Wurzeln geschlagen",
        "Mittlerweile sitzt's bei dir",
    ),
    last14Days = "Letzte 14 Tage",
    activityDays = "Aktivität der letzten 14 Tage: an %d Tagen gelernt",
    streakDays = "Serie: %d Tage",
    streakDaysOne = "Serie: %d Tag",
    dayOne = "Tag",
    dayMany = "Tage",
    widgetAwaitingTitle = "Spross öffnen",
    widgetAwaitingBody = "für frische Wörter",
)
