package net.spross.app

/**
 * UI chrome strings, rendered in the KNOWN language when chrome exists
 * (de/en today), otherwise en — design.md "Profile & onboarding".
 */
data class Chrome(
    val heuteTitle: String,
    val practice: String,
    val extraRound: String,
    val doneToday: String,
    val emptyState: String,
    val dueLabel: String,
    val newLabel: String,
    val activeLabel: String,
    val retentionLabel: String,
    val changeLanguages: String,
    val chooseTitle: String,
    val iSpeak: String,
    val iLearn: String,
    val conceptsSuffix: String,
    val letsGo: String,
    val backLabel: String,
    val check: String,
    val reveal: String,
    val next: String,
    val alsoPrefix: String,
    val typoNote: String,
    val answerPlaceholder: String, // %s = target language name
    val again: String,
    val hard: String,
    val good: String,
    val easy: String,
    val sessionDone: String,
    val summaryLine: String,       // %d neu · %d gefestigt · %d wiederholt
    val keepPracticing: String,
    val finish: String,
    val pluralEquals: String,
    val pluralOnly: String,
    val pluralPrefix: String,
) {
    companion object {
        fun forSource(source: String): Chrome = if (source == "de") DE else EN

        private val DE = Chrome(
            heuteTitle = "Heute",
            practice = "Üben",
            extraRound = "Extra-Runde",
            doneToday = "Für heute geschafft!",
            emptyState = "Die Box wächst, während dein Material sitzt.",
            dueLabel = "fällig",
            newLabel = "neu",
            activeLabel = "aktive Karten",
            retentionLabel = "Behalten",
            changeLanguages = "Sprachen ändern",
            chooseTitle = "Was möchtest du lernen?",
            iSpeak = "Ich spreche",
            iLearn = "Ich lerne",
            conceptsSuffix = "Begriffe",
            letsGo = "Los geht's",
            backLabel = "Zurück",
            check = "Prüfen",
            reveal = "Aufdecken",
            next = "Weiter",
            alsoPrefix = "auch:",
            typoNote = "Kleiner Tippfehler – zählt!",
            answerPlaceholder = "In %s …",
            again = "Nochmal",
            hard = "Schwer",
            good = "Gut",
            easy = "Leicht",
            sessionDone = "Geschafft!",
            summaryLine = "%d neu · %d gefestigt · %d wiederholt",
            keepPracticing = "Weiter üben",
            finish = "Fertig",
            pluralEquals = "= Pl.",
            pluralOnly = "nur Pl.",
            pluralPrefix = "Pl. ",
        )

        private val EN = Chrome(
            heuteTitle = "Today",
            practice = "Practice",
            extraRound = "Extra round",
            doneToday = "Done for today!",
            emptyState = "The box grows while your material sits.",
            dueLabel = "due",
            newLabel = "new",
            activeLabel = "active cards",
            retentionLabel = "Retention",
            changeLanguages = "Change languages",
            chooseTitle = "What do you want to learn?",
            iSpeak = "I speak",
            iLearn = "I learn",
            conceptsSuffix = "terms",
            letsGo = "Let's go",
            backLabel = "Back",
            check = "Check",
            reveal = "Reveal",
            next = "Next",
            alsoPrefix = "also:",
            typoNote = "Small typo – still counts!",
            answerPlaceholder = "In %s …",
            again = "Again",
            hard = "Hard",
            good = "Good",
            easy = "Easy",
            sessionDone = "Done!",
            summaryLine = "%d new · %d strengthened · %d reviewed",
            keepPracticing = "Keep practicing",
            finish = "Finish",
            pluralEquals = "= pl.",
            pluralOnly = "pl. only",
            pluralPrefix = "pl. ",
        )
    }
}
