package net.spross.app

/**
 * The English chrome table, and the one every source without chrome of its own falls
 * back to ([Chrome.forSource]). Wording follows the iOS String Catalog key for key.
 */
internal val ChromeEn = Chrome(
    heuteTitle = "Today",
    practice = "Practice",
    extraRound = "Extra round",
    doneToday = "Done for today!",
    emptyState = "The box grows while your material sits.",
    dueLabel = "due",
    newLabel = "new",
    consolidatedLabel = "consolidated",
    freshLabel = "fresh",
    changeLanguages = "Change languages",
    chooseTitle = "What do you want to learn?",
    iSpeak = "I speak",
    iLearn = "I learn",
    letsGo = "Let's go",
    backLabel = "Back",
    check = "Check",
    reveal = "Reveal",
    next = "Next",
    alsoPrefix = "also:",
    typoNote = "Small typo – still counts!",
    otherWordNote = "By the way: %1\$s means “%2\$s”",
    answerPlaceholder = "In %s …",
    again = "Again",
    hard = "Hard",
    good = "Good",
    easy = "Easy",
    unknown = "Unknown",
    sessionDone = "Done!",
    summaryLine = "%d new · %d strengthened · %d reviewed",
    keepPracticing = "Keep practicing",
    finish = "Finish",
    pluralEquals = "= pl.",
    pluralOnly = "pl. only",
    pluralPrefix = "pl. ",
    readAloud = "Read words aloud",
    stateOn = "on",
    stateOff = "off",
    pronounce = "Pronounce",
    aboutButton = "About",
    audioToggle = "Read words aloud",
    audioToggleHint = "Read words aloud during review. Tapping a word speaks it " +
        "again — even when read-aloud is off.",
    creditsTitle = "Voices & licences",
    creditsRecordings = "%d recordings",
    creditsUnmodified = "Recordings shipped unmodified",
    creditsCommons = "Recordings from Wikimedia Commons",
    trainingTitle = "Workshop",
    trainingSubtitle = "Free practice — no schedule, no limit",
    lettersTitle = "Letters",
    lettersHear = "Which letter is this?",
    lettersSpell = "What's missing in the word?",
    lettersDictation = "Write what you hear",
    letterChoice = "Letter %s",
    replayPrompt = "Play it again",
    promptInLanguage = "in %s",
    level = "Level %d",
    streak = "🔥 %d in a row",
    typoCorrection = "Almost! Correct spelling: %s",
    heardInstead = "You heard: %s",
    audioOff = "Sound is off",
    enableSound = "Turn sound on",
    tasksDoneOne = "1 task 🎯",
    tasksDone = "%d tasks 🎯",
    bestStreak = "Best streak: 🔥 %d in a row",
    answerCorrect = "Correct",
    answerWrong = "Wrong",

    close = "Close",
    numbersTitle = "Numbers",
    numbersPage = "Numbers · %s",
    lettersPage = "Letters · %s",
    overviewPractice = "Practice",
    overviewStart = "Start",
    numbersReference = "How this language counts",
    numbersNotes = "What to watch out for",
    numberSections = mapOf(
        "ones" to "Zero to nine",
        "teens" to "Ten to nineteen",
        "tens" to "The tens",
        "twenties" to "The twenties",
        "compounds" to "Put together",
        "hundreds" to "The hundreds",
        "places" to "Thousand, million, billion",
        "forms" to "Other notations",
    ),
    variantClock = "Time",
    variantPhrases = "Sentences",
    variantForms = "Forms",
    modifierReverse = "Reversed",
    modifierReverseHint = "The reading is shown, the digits are owed.",
    modifierFast = "Fast",
    modifierFastHint = "One clean answer per rung instead of two.",
    modifierMix = "Mixed up",
    modifierMixHint = "The direction flips every task, " +
        "and forms grow to the size the numbers reached.",
    combineLocked = "Several in one run, once everything is unlocked.",
    unlockPrefix = "Unlocks at:",

    digitsOne = "🔢 1 digit",
    digitsMany = "🔢 %d digits",
    record = "Record %d",
    streakSpoken = "Streak: %d in a row",
    recordSpoken = ", record %d",
    answerDigits = "In digits …",
    newPlace = "New place: %s",
    lookUp = "Look up numbers",
    newRecord = "New record!",

    stageChoiceEasy = "Four tiles",
    stageChoiceEasyHint = "Find the letter you heard among four",
    stageChoiceConfusable = "Lookalike tiles",
    stageChoiceConfusableHint = "The same choice, between letters that are easy to mix up",
    stageTyped = "Typing",
    stageTypedHint = "Write the letter yourself, with nothing to pick from",
    stageDictation = "Dictation",
    stageDictationHint = "Write whole words from your own box by ear",
    stageDictationLocked = "Needs more consolidated words this device can read out",
    stageEntry = "your run starts here",
    lettersUnavailable = "This device cannot say a letter yet — " +
        "that needs a voice for the language.",
    alphabetTitle = "Alphabet",
    alphabetSpeakName = "Hear the name",
    alphabetSpeakExample = "Hear the example",

    boxTitle = "The box",
    boxNav = "Box",
    boxSubtitle = "%1\$d of %2\$d cards in progress",
    ownWordsTitle = "Your own words",
    ownWordsExplainer = "Your own words stand in an area of their own. " +
        "A growing catalog never touches them.",
    packArea = "Add to box (%d)",
    packDone = "All packed",
    packWord = "Pack this word",
    packedWord = "Packed",
    suspended = "Paused",
    wake = "Wake",
    progressFresh = "%d fresh",
    phrasesLocked = "%d sentences",
    phrasesLockedSpoken = "%d sentences locked",
    stateExpanded = "expanded",
    stateCollapsed = "collapsed",
    phaseLearning = "Learning",
    phaseReview = "Solid",
    phaseRelearning = "Shaky",

    search = "Search",
    searchPlaceholder = "Word or area",
    searchHint = "Words in either language, and the names of the areas.",
    searchAreas = "Areas",
    searchWords = "Words",
    searchNothing = "Nothing for “%s” in the box.",
    searchWriteOwn = "Write “%s” yourself",
    searchClear = "Clear search",

    ownWordTitle = "Your own word",
    ownWordInLanguage = "In %s",
    ownWordPicture = "Picture (optional)",
    ownWordAdd = "Add",
    ownWordRemove = "Delete word",

    settingsTitle = "Settings",
    profileHint = "Switching the language you speak keeps all your progress; " +
        "each language you learn has its own box.",
    resetButton = "Reset box …",
    resetHint = "Deletes this box's progress and history — the content stays.",
    resetConfirm = "Delete all learning progress for %s and start over with the first words?",
    cancel = "Cancel",
    reset = "Reset",

    copyPrompt = "Write it once in %s …",
    copyMismatch = "Not quite — the word is right above.",
    skipStep = "Skip",

    caughtUpTitle = "Nothing's due right now",
    dayReviews = "%d reviews",
    dayReviewsOne = "1 review",
    dayNewCards = "%d newbies",
    dayNewCardsOne = "1 newbie",
    dayConsolidated = "%d solidified",
    dayAhead = "%d refreshers",
    dayAheadOne = "1 refresher",
    tomorrowPacked = "Your packed words are in the next round.",
    tomorrowFresh = "Fresh cards tomorrow. See you then! 👋",
    tomorrowDue = "Tomorrow you can review %d cards.",

    headlineReviews = listOf(
        "Your round is ready",
        "A stack is ready",
        "The box has something for you",
    ),
    headlineWarmUp = listOf(
        "Time for a refresher",
        "A reunion with familiar words",
        "A quick pass through the familiar",
    ),
    headlineFreshSet = listOf(
        "Up for some new words?",
        "Newbies on the table",
        "A few newbies to get to know",
    ),
    sessionSomeCards = "A few cards for you.",
    sessionHeldBack = "%d more cards are still waiting for you.",
    sessionStart = "Let's go!",

    emptyBoxTitle = "Your box is still empty",
    emptyBoxMessage = "Add an area directly — the box grows while your material sits.",
    emptyBoxAction = "Go to box",

    errorTitle = "Oops",
    errorCatalogMissing = "The content could not be loaded. (catalog missing from the app)",
    errorContentUnavailable = "The content could not be loaded. (%s)",
    errorUnknownProfile = "Unknown language profile (%1\$s → %2\$s).",
    errorResetFailed = "Reset failed. (%s)",

    roundNew = "%d new",
    roundConsolidated = "%d consolidated",
    roundReviewed = "%d reviewed",
    roundAllDone = "All done",
    restHint = "Not much is sticking today — a tired head keeps nothing. " +
        "Tomorrow will go easier.",
    streakRecord = "Your longest run yet!",

    growthGrew = "Some of it sticks today too",
    growthOpened = "Your first words in good soil",
    growthBlooming = listOf(
        "Saying what you sowed",
        "You've brought this into bloom",
        "Your tending shows",
    ),
    growthSown = listOf(
        "You've sown here",
        "You've got this sprouting",
        "You're planting, word by word",
    ),
    growthGrown = listOf(
        "You've grown what you can say",
        "Your words root deeper now",
        "Words are settling in",
    ),

    progressTitle = "Progress",
    last14Days = "Last 14 days",
    activityDays = "Activity over the last 14 days: practiced on %d days",
    streakDays = "Streak: %d days",
    streakDaysOne = "Streak: 1 day",
    dayOne = "day",
    dayMany = "days",
)
