package net.spross.kern.trainer

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Golden-vector equality against resources/trainer-golden.json, copied
 * VERBATIM from the v1 Swift suite (originally generated by running the
 * prototype's extracted JS functions with node — never hand-derived).
 */
class TrainerGoldenTests {

    @Serializable
    private data class GermanYear(val display: String, val accepted: List<String>)

    @Serializable
    private data class GermanClockEntry(val standard: String, val regional: String)

    @Serializable
    private data class Fixture(
        val germanNumbers: Map<String, String>,
        val swahiliNumbers: Map<String, String>,
        val germanYears: Map<String, GermanYear>,
        val swahiliYears: Map<String, String>,
        val germanClock: Map<String, GermanClockEntry>,
        val swahiliClock: Map<String, String>,
    )

    private val fixture: Fixture by lazy {
        val stream = checkNotNull(javaClass.classLoader.getResourceAsStream("trainer-golden.json"))
        Json.decodeFromString<Fixture>(stream.readBytes().decodeToString())
    }

    private fun parseClock(key: String): Pair<Int, Int> {
        val (h, m) = key.split(":").map { it.toInt() }
        return h to m
    }

    @Test
    fun germanNumbersMatchGolden() {
        assertEquals(38, fixture.germanNumbers.size)
        for ((key, expected) in fixture.germanNumbers) {
            val task = Trainer.number(key.toLong(), "de")
            assertEquals(expected, task.display, "n=$key")
            assertEquals(listOf(expected), task.accepted, "n=$key")
            assertEquals(key, task.prompt)
        }
    }

    @Test
    fun swahiliNumbersMatchGolden() {
        assertEquals(38, fixture.swahiliNumbers.size)
        for ((key, expected) in fixture.swahiliNumbers) {
            val task = Trainer.number(key.toLong(), "sw")
            assertEquals(expected, task.display, "n=$key")
            assertEquals(listOf(expected), task.accepted, "n=$key")
        }
    }

    @Test
    fun germanYearsMatchGolden() {
        assertEquals(10, fixture.germanYears.size)
        for ((key, expected) in fixture.germanYears) {
            val task = Trainer.year(key.toLong(), "de")
            assertEquals(expected.display, task.display, "y=$key")
            assertEquals(expected.accepted, task.accepted, "y=$key")
        }
    }

    @Test
    fun swahiliYearsArePlainCardinalReadings() {
        assertEquals(10, fixture.swahiliYears.size)
        for ((key, expected) in fixture.swahiliYears) {
            val task = Trainer.year(key.toLong(), "sw")
            assertEquals(expected, task.display, "y=$key")
            assertEquals(listOf(expected), task.accepted, "y=$key")
        }
    }

    @Test
    fun germanClockMatchesGolden() {
        assertEquals(120, fixture.germanClock.size)
        for ((key, expected) in fixture.germanClock) {
            val (h, m) = parseClock(key)
            val task = Trainer.clock(h, m, "de")
            assertEquals(key, task.prompt)
            assertEquals(expected.standard, task.display, "t=$key")
            val golden = mutableListOf(expected.standard)
            if (expected.regional != expected.standard) golden += expected.regional
            // Round hours also accept colloquial "um zehn" (regional is "punkt <hour>").
            if (m == 0 && expected.standard.endsWith("Uhr")) {
                golden += "um " + expected.regional.removePrefix("punkt ")
            }
            // Golden values lead the accepted list unchanged. What follows them is
            // accepted-only and free to grow — this asserts what must be IN that tail
            // (the formal 24-hour reading, plus "vierundzwanzig Uhr" at 0:00), not what
            // else may be, so the day-part and "Minuten" readings need no restating here.
            assertEquals(golden, task.accepted.take(golden.size), "t=$key")
            val tail = task.accepted.drop(golden.size)
            val h24 = GermanNumbers.cardinal(h.toLong()) + " Uhr" +
                (if (m == 0) "" else " " + GermanNumbers.cardinal(m.toLong()))
            if (h24 !in golden) assertEquals(h24, tail.firstOrNull(), "t=$key")
            if (h == 0 && m == 0) assertTrue("vierundzwanzig Uhr" in tail, "t=$key")
            assertTrue(tail.none { it in golden }, "t=$key: golden reading repeated in $tail")
        }
    }

    @Test
    fun swahiliClockMatchesGolden() {
        assertEquals(120, fixture.swahiliClock.size)
        for ((key, expected) in fixture.swahiliClock) {
            val (h, m) = parseClock(key)
            val task = Trainer.clock(h, m, "sw")
            assertEquals(expected, task.display, "t=$key")
            // Period is optional: the bare reading (no day period) and the
            // canonical display are both accepted; overlap hours add a second.
            val base = expected.split(" ").dropLast(1).joinToString(" ")
            assertEquals(base, task.accepted.first(), "t=$key")
            assertTrue(expected in task.accepted, "t=$key")
            assertTrue(task.gloss?.contains("Saa") == true)
        }
    }
}
