"use strict";

// Mailing-list endpoint — empty until an account exists; wiring notes in docs/website.md.
// Buttondown-shaped: "https://buttondown.com/api/emails/embed-subscribe/<slug>"
const SIGNUP_ENDPOINT = "";

// Language rows mirror catalog/languages.json (name, flag); speech is a web-only fact.
const LANGS = [
  { code: "de", name: "Deutsch", flag: "🇩🇪", speech: "de-DE" },
  { code: "en", name: "English", flag: "🇬🇧", speech: "en-GB" },
  { code: "es", name: "Español", flag: "🇪🇸", speech: "es-ES" },
  { code: "sw", name: "Kiswahili", flag: "🇹🇿", speech: "sw" },
  { code: "uk", name: "Українська", flag: "🇺🇦", speech: "uk-UA" },
];

const web = globalThis.kern.net.spross.kern.web;
const WebTrainer = web.WebTrainer;

const MAX_LEVEL = 4; // the web taste stops at thousands; the app climbs to 10 digits
const NUDGE_AFTER = 10;

const $ = (id) => document.getElementById(id);
const reducedMotion = matchMedia("(prefers-reduced-motion: reduce)").matches;

// ---------- language pick ----------

let lang = null;
let drill = null;

const chipsHost = document.querySelector(".lang-chips");
for (const l of LANGS) {
  const chip = document.createElement("button");
  chip.className = "chip";
  chip.type = "button";
  chip.setAttribute("aria-pressed", "false");
  chip.textContent = `${l.flag} ${l.name}`;
  chip.addEventListener("click", () => pickLanguage(l, chip));
  chipsHost.appendChild(chip);
}

function pickLanguage(l, chip) {
  lang = l;
  for (const c of chipsHost.children) c.setAttribute("aria-pressed", String(c === chip));
  $("primer-toggle").hidden = false;
  $("start-drill").hidden = false;
  $("primer").hidden = true;
  $("primer-toggle").textContent = "Peek at the numbers first";
  $("run").hidden = true;
  $("summary").hidden = true;
  renderPrimer();
}

// ---------- primer (generated by the kern, so never wrong) ----------

function primerRows(values) {
  return values
    .map((n) => `<tr><td class="n">${n}</td><td class="w">${WebTrainer.spellNumber(n, lang.code)}</td></tr>`)
    .join("");
}

function renderPrimer() {
  const small = Array.from({ length: 13 }, (_, i) => i);
  const tens = [20, 30, 40, 50, 60, 70, 80, 90];
  const built = [21, 47, 135, 999, 1000];
  const hundred = WebTrainer.placeValueHint(3, lang.code);
  const thousand = WebTrainer.placeValueHint(4, lang.code);
  $("primer").innerHTML = `
    <div class="cols">
      <table><caption>The seeds</caption>${primerRows(small)}</table>
      <table><caption>The tens</caption>${primerRows(tens)}</table>
      <table><caption>Built numbers</caption>${primerRows(built)}</table>
    </div>
    <p class="place">The place words to watch for: <strong>${hundred}</strong> (hundreds) and <strong>${thousand}</strong> (thousands).</p>`;
}

$("primer-toggle").addEventListener("click", () => {
  const p = $("primer");
  p.hidden = !p.hidden;
  $("primer-toggle").textContent = p.hidden ? "Peek at the numbers first" : "Tuck the numbers away";
});

// ---------- run state (page-owned policy, mirroring the iOS session) ----------

const run = {
  level: 1,
  streak: 0,
  best: 0,
  cleanAtLevel: 0,
  outcomes: [], // "ok" | "near" | "miss"
  seenDigits: new Set(),
  task: null,
  prevPrompt: null,
  locked: false,
  hintUsed: false,
  nudged: false,
  muted: false,
};

$("start-drill").addEventListener("click", startRun);
$("again").addEventListener("click", startRun);

function startRun() {
  drill = new web.NumbersDrill(lang.code, Date.now() % 0x7fffffff);
  Object.assign(run, {
    level: 1, streak: 0, best: 0, cleanAtLevel: 0, outcomes: [],
    seenDigits: new Set(), task: null, prevPrompt: null,
    locked: false, hintUsed: false, nudged: false,
  });
  $("lang-pick").hidden = true;
  $("summary").hidden = true;
  $("run").hidden = false;
  $("progress").innerHTML = "";
  $("tens-link").hidden = !WebTrainer.tensReference(lang.code);
  nextTask();
}

function nextTask() {
  let task = drill.sample(run.level);
  if (task.prompt === run.prevPrompt) task = drill.sample(run.level); // no back-to-back repeat
  run.task = task;
  run.prevPrompt = task.prompt;
  run.locked = false;
  run.hintUsed = false;

  $("numeral").textContent = task.promptDisplay;
  $("reveal").hidden = true;
  $("correction").hidden = true;
  $("tens-card").hidden = true;
  $("answer").dataset.state = "idle";
  $("feedback").textContent = "";
  const input = $("answer-input");
  input.value = "";
  input.disabled = false;
  input.placeholder = `… in ${lang.name}`;
  input.focus({ preventScroll: true });
  setAction("Reveal");

  const hint = WebTrainer.placeValueHint(task.digits, lang.code);
  const fresh = hint && !run.seenDigits.has(task.digits);
  $("hint").hidden = !fresh;
  if (fresh) $("hint").textContent = `New place: ${hint}`;
  run.seenDigits.add(task.digits);
  updateHead();
}

function updateHead() {
  const bits = [`${run.level} ${run.level === 1 ? "digit" : "digits"}`];
  if (run.streak > 0) bits.push(`streak ${run.streak}`);
  if (run.best > run.streak) bits.push(`best ${run.best}`);
  const line = $("streak-line");
  line.textContent = bits.join(" · ");
  line.dataset.live = String(run.streak > 0);
}

function setAction(label) {
  $("main-action").textContent = label;
}

// ---------- answering ----------

const input = $("answer-input");

input.addEventListener("input", () => {
  if (run.locked) return;
  setAction(input.value.trim() ? "Check" : "Reveal");
  // Finishing the word IS the answer — but only once no accepted form still extends it.
  const typed = input.value.trim();
  if (!typed) return;
  const verdict = drill.grade(typed, run.task);
  if (verdict.verdict === "exact" && !stillGrowing(typed)) settle("exact", null, 450);
});

input.addEventListener("keydown", (e) => {
  if (e.key === "Enter") { e.preventDefault(); $("main-action").click(); }
});

function normLite(s) {
  return s.normalize("NFC").toLowerCase().replace(/ß/g, "ss").replace(/[-'’]/g, "")
    .replace(/[^\p{L}\p{N}]+/gu, " ").trim().replace(/\s+/g, " ");
}

function stillGrowing(typed) {
  const t = normLite(typed);
  return Array.from(run.task.accepted).some((a) => {
    const n = normLite(a);
    return n !== t && n.startsWith(t);
  });
}

$("main-action").addEventListener("click", () => {
  if (run.locked) { advance(); return; }
  const typed = input.value.trim();
  if (!typed) { settle("wrong", null, null); return; } // Reveal = a miss
  const verdict = drill.grade(typed, run.task);
  if (verdict.verdict === "exact") settle("exact", null, 1200);
  else if (verdict.verdict === "typo") settle("typo", verdict.corrected, null);
  else settle("wrong", null, null);
});

function settle(kind, corrected, autoAdvanceMs) {
  run.locked = true;
  input.disabled = true;
  $("hint").hidden = true;
  const clean = kind === "exact" && !run.hintUsed;

  if (kind === "exact") {
    run.outcomes.push(run.hintUsed ? "near" : "ok");
    $("answer").dataset.state = "exact";
    $("feedback").textContent = "Right!";
    if (clean) {
      run.streak += 1;
      run.best = Math.max(run.best, run.streak);
      run.cleanAtLevel += 1;
      if (run.cleanAtLevel >= 2 && run.level < MAX_LEVEL) { run.level += 1; run.cleanAtLevel = 0; }
    }
  } else if (kind === "typo") {
    run.outcomes.push("near");
    $("answer").dataset.state = "typo";
    $("correction").hidden = false;
    $("correction").innerHTML = "";
    $("correction").append(speakable(corrected));
    $("feedback").textContent = `Almost — ${corrected}`;
    speak(corrected);
  } else {
    run.outcomes.push("miss");
    run.streak = 0;
    run.cleanAtLevel = 0;
    run.level = Math.max(1, run.level - 1);
    $("answer").dataset.state = "wrong";
    $("reveal").hidden = false;
    $("reveal").innerHTML = "";
    $("reveal").append(speakable(run.task.display));
    $("feedback").textContent = `It reads: ${run.task.display}`;
    if (!$("tens-link").hidden) showTens(false);
    speak(run.task.display);
  }

  paintProgress();
  updateHead();

  // why: under reduced motion a timed advance would snatch the feedback away —
  // the explicit Next button replaces the timer, like the app under VoiceOver.
  if (autoAdvanceMs != null && !reducedMotion) {
    setTimeout(advance, autoAdvanceMs);
  } else {
    setAction("Next");
    $("main-action").focus();
  }
  maybeNudge();
}

function advance() {
  if (!run.locked) return;
  nextTask();
}

function paintProgress() {
  const seg = document.createElement("span");
  seg.className = run.outcomes[run.outcomes.length - 1];
  $("progress").appendChild(seg);
}

function maybeNudge() {
  if (run.nudged || run.outcomes.length < NUDGE_AFTER) return;
  run.nudged = true;
  $("nudge").hidden = false;
}

$("nudge-close").addEventListener("click", () => { $("nudge").hidden = true; });

// ---------- tens reference (Swahili) ----------

$("tens-link").addEventListener("click", () => showTens(true));

function showTens(costsTheRamp) {
  const tens = WebTrainer.tensReference(lang.code);
  if (!tens) return;
  $("tens-card").hidden = false;
  $("tens-card").textContent = Array.from(tens).join(" · ");
  if (costsTheRamp && !run.locked) run.hintUsed = true; // a looked-up answer never ramps
}

// ---------- finish / summary ----------

$("finish").addEventListener("click", () => {
  const n = run.outcomes.length;
  if (n === 0) { backToPick(); return; }
  $("run").hidden = true;
  const tier = run.best >= 10 ? "🏆" : run.best >= 5 ? "🎉" : run.best >= 2 ? "💪" : "🌱";
  $("summary-emoji").textContent = tier;
  $("summary-count").textContent = `${n} ${n === 1 ? "number" : "numbers"}`;
  $("summary-best").textContent = run.best > 0 ? `Best streak: ${run.best}` : "Every seed starts somewhere.";
  $("summary-lang").textContent = `Numbers · ${lang.name}`;
  $("summary").hidden = false;
});

function backToPick() {
  $("run").hidden = true;
  $("summary").hidden = true;
  $("lang-pick").hidden = false;
}

$("switch-lang").addEventListener("click", backToPick);

// ---------- speech (answer-side only, like the app) ----------

let voice;

function findVoice() {
  if (!("speechSynthesis" in window) || !lang) return null;
  return speechSynthesis.getVoices().find((v) => v.lang.replace("_", "-").startsWith(lang.code)) || null;
}

if ("speechSynthesis" in window) {
  speechSynthesis.addEventListener?.("voiceschanged", () => { voice = findVoice(); });
}

function speak(text) {
  if (run.muted || !("speechSynthesis" in window)) return;
  voice = voice && voice.lang.startsWith(lang.code) ? voice : findVoice();
  if (!voice) return;
  const u = new SpeechSynthesisUtterance(text);
  u.voice = voice;
  u.lang = lang.speech;
  setTimeout(() => speechSynthesis.speak(u), 300); // let the moment land first
}

function speakable(text) {
  const frag = document.createDocumentFragment();
  frag.append(text);
  if ("speechSynthesis" in window && findVoice()) {
    const btn = document.createElement("button");
    btn.className = "icon-btn";
    btn.type = "button";
    btn.textContent = "🔈";
    btn.setAttribute("aria-label", `Hear “${text}”`);
    btn.addEventListener("click", () => { const m = run.muted; run.muted = false; speak(text); run.muted = m; });
    frag.append(" ", btn);
  }
  return frag;
}

$("mute").addEventListener("click", () => {
  run.muted = !run.muted;
  $("mute").textContent = run.muted ? "🔇" : "🔊";
  $("mute").setAttribute("aria-pressed", String(run.muted));
});

// ---------- mailing list ----------

$("signup-form").addEventListener("submit", async (e) => {
  e.preventDefault();
  const note = $("signup-note");
  const email = new FormData(e.target).get("email");
  if (!SIGNUP_ENDPOINT) {
    note.textContent = "The list isn't open quite yet — write to feedback@spross.net and we'll plant you in by hand.";
    return;
  }
  try {
    await fetch(SIGNUP_ENDPOINT, {
      method: "POST",
      mode: "no-cors",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({ email }),
    });
    note.textContent = "Welcome, Sprössling. 🌱 Check your inbox to confirm.";
    note.className = "note thanks";
    e.target.hidden = true;
  } catch {
    note.textContent = "That didn't take root — please try again, or write to feedback@spross.net.";
  }
});
